### ISSUE TITLE
Datensätze: Löschfunktion mit modalem Dialog

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#10]
Man soll einen gewählten Datensatz nach Sicherheitsabfrage in modalem Dialog löschen können.

**Comment by Nullmann** [comment]
Habe ich hinzugefügt, aber noch auskommentiert, weil es noch keine Möglichkeit gibt, einen neuen Datensatz anzulegen.

**Comment by Nullmann** [comment]
Die Ansichten, die zu dem Datensatz gehören, sollen auch gelöscht werden

**Comment by SteffenPegenau** [comment]
Auch alle Collections mit
collectionId + META_DATA_PART (definiert in lib_view.js)
beginnen.
(Diese beinhalten die Meta-Informationen)

**Comment by JuliaH1** [comment]
Löschen funktioniert zwar, der Datensatz verschwindet aber erst, wenn man die Seite mit den Datensätzen neu lädt
