### ISSUE TITLE
Vorgärten unterscheiden

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#100]
Wie unterscheidet zwischen den Eingängen und den Ausgängen bzw. den zwei Vorgärten? Vorschlag: zwei unterschiedliche Farben

**Comment by thuylinhluu** [comment]
Wie bei einer Straße sind eingehende Verbindungen rechts und ausgehende Verbindungen links

**Comment by JuliaH1** [comment]
Dann wäre es gut, das irgendwie erkenntlich zu machen. Mir war das von vornherein nicht klar. Vielleicht in der Dropbox die Info, welche die Eingänge welche die Ausgänge sind

**Comment by JuliaH1** [comment]
Oder statt in der Dropbox das zu vermerken, kann ich auch einen Hinweis machen

**Comment by MarcelMP** [comment]
Habe jetzt einen Hinweis unter die Checkbox gesetzt. ist das so in Ordnung?

**Comment by JuliaH1** [comment]
*nicht Dropbox sondern Dropdown-Menü :grin:
