### ISSUE TITLE
Vogelperspektive bugt

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#101]

**Comment by thuylinhluu** [comment]
verstehe ich nicht

**Comment by JuliaH1** [comment]
Wenn man die Stadt verschiebt, dreht und macht, und dann auf die Vogelperspektive geht, "wackelt" die Kamera, oder die Sicht ist zu nah an der Stadt, oder einmal wurde die Stadt von unten betrachtet, also den Boden

**Comment by thuylinhluu** [comment]
das kommt vor, weil du die Stadt drehst und während sie noch am drehen ist du dann schnell auf "Vogelperspektive" klickst. Dann dreht die sich noch irgendwie weiter während die noch in der Vogelperspektive ist.

Wenn die Sicht zu nah ist, kann man wegzoomen. Es ist ja nur dafür gedacht, dass man da nicht ewig die Stadt so dreht, bis sie endlich oben ist.

Dass die Stadt von unten betrachtet wurde, ist mir noch nicht vorgekommen.

**Comment by JuliaH1** [comment]
Es passiert auch, wenn die Stadt still steht

**Comment by thuylinhluu** [comment]
Seltsam - bei mir nicht

**Comment by thuylinhluu** [comment]
Probiers nochmal. Passierts immernoch oder kann man den Issue schließen?

**Comment by JuliaH1** [comment]
Klappt super! :+1:
