### ISSUE TITLE
WebGL: Aktuelle Ansicht - Link nicht immer korrekt

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#104]
Liegt der Client nicht direkt im Root-Verzeichnis des Web-Servers ist der Link nicht korrekt.

Beispiel:
Auf unserem Web-Server sieht die Adresse (ungefähr) so aus:
http://127.0.0.1:8080/#/views/RuVBeispiel

In der aktuellen Anleitung empfehlen wir die Auslieferung des Web-Clients mit RESTHeart im Unterordner datacity. Dann sieht der Link so aus:
http://127.0.0.1:8080/datacity/#/views/RuVBeispiel
Der generierte Link sieht so aus:
http://127.0.0.1:8080/#/storedView?webGLSettings=...
Er müsste aber so lauten:
http://127.0.0.1:8080/datacity/#/storedView?webGLSettings=...

**Comment by thuylinhluu** [comment]
Ich hab sowas ja nicht lokal. Ist der Link denn nun richtig?
