### ISSUE TITLE
Suchfunktion nicht so schön

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#105]
Wenn man das Gebäude in die Suche eingibt und auf den Button klickt, wird das Gebäude zwar makiert, aber die Kamera zoomt so nah ran, dass man einmal rauszoomen muss, um das gesuchte Gebäude zu sehen. Und wenn man nach der Eingabe Enter drückt, statt den Button, wird nur das Gebäude makiert. So ne Enter-Eingabe empfinde ich als "intuitiv", und man sollte mit dem Drücken auf Enter den Button betätigen und somit auch die Kamera positionieren.

Und ein Vorschlag wäre vielleicht, darüber lässt sich aber diskutieren: Vielleicht die Kamera bisschen schräg nach oben verdrehen, um einen besseren Blick auf das Gebäude zu bekommen? Zur Zeit ist es eine frontale Sicht, sodass manche Gebäude im Weg stehen.

**Comment by thuylinhluu** [comment]
Guck mal, ob es jetzt so passt

**Comment by JuliaH1** [comment]
Sieht super aus
