### ISSUE TITLE
[1] Windows Paket

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#107]
MongoDB, RESTHeart, dist, admin-tool

Ausführbare .exe

Mit Batch-Datei?

**Comment by Nullmann** [comment]
Alles Wichtige läuft über diese Repo:
https://github.com/Data-City/WindowsPaket/issues

**Comment by JuliaH1** [comment]
Das Windows Paket funktioniert ja, kann man also den Issue schließen? :raised_hands: :smile:

**Comment by Nullmann** [comment]
Denke ja, einzelne Änderungen/Verbessrungsvorschläge können dann im dazugehörigen Repo hinterlegt werden:
https://github.com/Data-City/WindowsPaket/issues
