### ISSUE TITLE
Von gewähltem Datensatz zu seinen Ansichten

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#11]
Ein gewählter Datensatz soll sich auch auf die Ansichten auswirken

**Comment by Nullmann** [comment]
Genauere Beschreibung (aus deiner wurde ich direkt nicht schlau): Die Ansichten-Tabelle nach gewähltem Datensatz filtern.

**Comment by SteffenPegenau** [comment]
Es sollte elegant und einfach möglich sein, von einem ausgewählten Datensatz zur Übersicht der Ansichten zu gelanden
