### ISSUE TITLE
Filterfunktion filtert nichts...

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#115]
Die Stadt verändert sich nicht, wenn man filtern möchte...
So habe ich zb die Filter eingestellt - und bei neuer Generierung der Stadt werden weiterhin die ungefilterten Daten dargestellt

![balballba](https://cloud.githubusercontent.com/assets/15839253/12698918/a3a16574-c7aa-11e5-9356-5dc2704836c0.png)

**Comment by Nullmann** [comment]
Hast du die Änderungen gespeichert?
Hast du versucht die Seite neu zu geladen? Viele Bugs lassen sich so beheben.

**Comment by JuliaH1** [comment]
Klar habe ich die Änderungen gespeichert, und beim Neuladen passiert nichts. Funktioniert es denn bei euch?
