### ISSUE TITLE
Blockbildung Nr. 3 bildet keine Blöcke

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#116]
Wenn man Blockbildung mit "Blöcke auswählen" machen möchte, dann wird mir die Datei wie bei allen anderen Blockbildungsmöglichkeiten übergeben...

**Comment by Nullmann** [comment]
Müsste mit den Änderungen für Issue #106 zu tun haben.

**Comment by Nullmann** [comment]
Wie erwartet funktioniert es wieder, weil #106 geschlossen wurde.
