### ISSUE TITLE
Verbindungsdatei Vorschau

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#117]
Denkt ihr, sowas ist praktisch? Dass man sich wie bei der Vorschau des Datensatzes die Datei mit den Verbindungen anzeigen lässt?

**Comment by thuylinhluu** [comment]
Ich würde sagen, wenn jemand Lust und Zeit hat, so eine Vorschau zu schreiben, kann er/sie das gerne machen. Wenn nicht, wäre es sicher auch nicht schlimm...

**Comment by Nullmann** [comment]
Ist nicht explizit gewollt, schließe ich also mal.
