### ISSUE TITLE
Lokal funktioniert es nicht eine Ansicht zu speichern

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#119]
![12633131_745982095534362_1065045592_o](https://cloud.githubusercontent.com/assets/15816473/12715638/ad823fd2-c8db-11e5-87c4-ddb032d5705a.jpg)
---
Screenshot ist von Zi bzw Linh

**Comment by thuylinhluu** [comment]
Hahahhaa gutes Stichwort - Speichern! Wir haben die Ansicht nicht gespeichert und deswegen gings nicht... =D =D
