### ISSUE TITLE
Nur die ersten 100 Daten werden dargestellt

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#123]

**Comment by SteffenPegenau** [comment]
Bezieht sich das auf die Vorschau oder tatsächlich auf die Stadtansicht?

**Comment by JuliaH1** [comment]
Sowohl auf die Vorschau als auch die Stadtansicht. Bei der Vorschau ist das ja ok, wenn wir da allgemein ein Limit von 100 Datensätzen setzen.

**Comment by SteffenPegenau** [comment]
Auch mit Blöcken?

Kann es sein, dass die 100 Einträge, die zunächst geholt wurden einfach durchgereicht werden, falls man keine Blöcke aktiviert?

Dann könnte die Lösung darin bestehen, die gleiche Aggregationspipeline wie bei der Blockbildung  zu durchlaufen, ohne Blöcke zu erstellen. Dann sollten alle Gebäude in einem Object City (oder so ähnlich) liegen.

**Comment by Nullmann** [comment]
Ohne Blockbildung werden die einfach nur weiter geleitet, das stimmt.

**Comment by SteffenPegenau** [comment]
Mit Blöcken funktioniert es bei einem großen Datensatz.

Das Bild sieht zunächst kaputt aus. Zoomt man hinein, sieht man jedoch >> 100 Gebäude
