### ISSUE TITLE
Stadtdarstellung beim Windows Paket funktioniert nicht

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#128]
Egal bei welchem Datensatz wird die Stadt nicht angezeigt und ein Syntax Error angezeigt, und ich verstehe das Problem nicht, die 11. Stelle in der ersten Zeile ist mitten im Wort strict drin...
![unbenannt](https://cloud.githubusercontent.com/assets/15839253/12884712/5a877786-ce60-11e5-9cf2-41aadd8f1e19.png)

**Comment by Nullmann** [comment]
Das hat sich doch mittlerweile erledigt, oder?
Außerdem müsste sowas ins Repo "Windows Paket".
Und das "use strict" ist bestimmt nicht der Fehler hier gewesen :D

**Comment by Nullmann** [comment]
Dies wurde mittlerweile behoben und der Fehler in der README hinterlegt?

**Comment by JuliaH1** [comment]
Jap, hat sich ja dann auch mit einem Neustart geregelt
