### ISSUE TITLE
Limits ermitteln

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#129]
Nach wenigen Minuten Wartezeit wird der Aufbau der Stadtansicht abgebrochen, wenn man die Blockbildung beim großen Datensatz aktiviert.

![fehlermeldung_blockbildung_grosse datensatze](https://cloud.githubusercontent.com/assets/15968962/12886226/18677fac-ce6c-11e5-9f21-fb78567d7ea5.png)

**Comment by Nullmann** [comment]
Manus Konsolenausgabe

![12698772_1111801812219652_1740356336_o](https://cloud.githubusercontent.com/assets/15816473/12886878/bb56b67a-ce70-11e5-88d0-7ff2a0c4948b.jpg)

**Comment by ManuelMueller1988** [comment]
Done.
80000-100000 werden flüssig dargestellt.
Fehlerbehandlung in Issue #205.
