### ISSUE TITLE
WebGL - Straßen

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#134]

**Comment by JuliaH1** [comment]
Das sieht ja schon super aus!! :smile 
Kann irgendwo festgehalten werden, muss nicht umbedingt im WebGL sein, kann auch in der Oberfläche bei der Auswahl der Verbindungen passieren, was die rote bzw schwarze Farbe der Straßen bedeutet? Und natürlich auch die Farbe der Vorgärten
