### ISSUE TITLE
Einbabe Benutzername+Passwort wird gefordert

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#137]
Zwischendurch taucht immer wieder der Dialog auf, der zur Eingabe von Benutzername und Passwort auffordert.

Da wir lokal arbeiten, könnte man das vielleicht lösen, indem man auch nicht-authentifizierten Nutzern den vollen Zugriff gibt.

Wenn es Probleme gibt, bitte nachfragen!

**Comment by Nullmann** [comment]
Das ist in der lokalen Version bereits gelöst und müsste auf dem Server noch in der security.yml in Restheart eingefügt werden.

**Comment by ZiZiWang** [comment]
Ja, bei lokalen Version wurde es nicht mehr aufgefordert

**Comment by Nullmann** [comment]
Hiermit schließe ich das Issue mal, mit weiterem Verweis auf #121 ;)
