### ISSUE TITLE
Lade-Anzeige einbauen

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#14]
Um dem Nutzer anzuzeigen, dass etwas geladen wird, soll eine Lade-Anzeige eingebaut werden.

Das ist vor allem bei langsamen Internetverbindungen oder großen Datensätzen wichtig.

Sowas gibt es - so weit ich weiß - auch von Angular. Stichwort: spinner

**Comment by Nullmann** [comment]
Das hier klingt doch vielversprechend und vor allem wenig Aufwand:
http://chieffancypants.github.io/angular-loading-bar/

**Comment by Nullmann** [comment]
Wenn man eine leere Dependancy zu einem Modul hinzufügt
angular.module('datacityApp', [''])
, dann zerstört das bereits die Seite. So kann man keine weiteren Dependancies hinzufügen. Liegt das an Yeoman?

**Comment by Nullmann** [comment]
Spinner wurde eingebaut
