### ISSUE TITLE
Datenaggregierung und Datenselektion zusammenführen

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#140]
Schritt 1 und 3 zusammenführen.

**Comment by SteffenPegenau** [comment]
Zunächst, ist zu prüfen, ob der Input der ersten Aggregationsstufe die 10 MB-Grenze übersteigen darf.

Konkret:
In der MongoDB-Shell über den BigData-Datensatz, Feld *Gender* aggregieren, **ohne** vorher etwas mit $project oder $match zu filtern.

**Comment by JuliaH1** [comment]
Keine Zeit

**Comment by Nullmann** [comment]
Würde die Oberfläche verunschönern und im Hintergrund der Datenobergrenze ergibt es keine Verbesserungen
