### ISSUE TITLE
SQL-Statements zu den Namen der Schritte hinzufügen

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#141]

**Comment by JuliaH1** [comment]
Beim ersten zb. einfach nur (SELECT) oder schon bisschen ausführlicher: (SELECT...FROM...WHERE)?

**Comment by JuliaH1** [comment]
Meiner Meinung nach ist das somit abgeschlossen. Falls jemand etwas anders haben möchte oder so, kann der Issue wieder geöffnet werden.
