### ISSUE TITLE
Verbesserung zu den Straßen

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#143]
Hier fällt mir auf, dass die eine Straße um die komplette Stadt hinten rum läuft um zum Verbindungspartner zu gelangen. Ich verstehe, dass die Straße komplett raus aus dem großen "hellen" Package muss und wie ich das hier verstehe, können die Straßen nur, wenn sie ein package verlassen, an der hier unteren Kante raus. Aber ist es machbar, dass die Straße nicht hinten rum verläuft, sondern hier an der rechten Kante des hellen Distrikts raus geht? Das ist ja auch dann der kürzere Weg
![unbenannt](https://cloud.githubusercontent.com/assets/15839253/13044142/c3694ba0-d3cc-11e5-92ee-4fe328de917f.png)

**Comment by Nullmann** [comment]
Geschiet dies in der aktuellen Version immer noch?
Ansonsten würde ich sagen, dass die Straßen genau das machen, was sie machen sollen und hier kein Änderungsbedarf besteht.

**Comment by JuliaH1** [comment]
Ja, genau das passiert immer noch
