### ISSUE TITLE
BigData Dimensionen buggen

### ISSUE THREAD

**Issue by MarcelMP** [Data-City/client#144]
![bug](https://cloud.githubusercontent.com/assets/15869627/13051927/30f7960c-d3fc-11e5-89e7-33594e0f8520.PNG)

**Comment by MarcelMP** [comment]
Wenn man ID als Name für die Dimension wählt und die Änderung speichert, erkennt er das Feld nicht und gibt die obige Fehlermeldung aus

**Comment by Nullmann** [comment]
Klappt im aktuellen Datensatz "BigDataMitverbindungen" immer noch nicht -> Dadurch klappen die Verbindungen nicht.

**Comment by Nullmann** [comment]
Generell kann man in der Select-List "ID" nichts auswählen. Wählt man etwas aus, speichert die Ansicht und lädt sie dann neu (deselektieren, neu selektieren), ist sie leer.

**Comment by JuliaH1** [comment]
Kann doch geschlossen werden, funktioniert einwandfrei. @MarcelMP bitte nochmal testen und ggf schließen

**Comment by Nullmann** [comment]
Der Issue selbst wurde behoben; das aufgetrene Problem wird in Issue #234 weiter behandelt.
