### ISSUE TITLE
Schritt 1: Beispieldaten sollten angezeigt werden

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#147]
Man hat am Anfang die Möglichkeit zum Preview, das ist gut.
Hilfreich wäre im Schritt 1 dann noch, wenn man neben den auswählbaren Spalten jeweils noch einen Beispielinhalt sehen könnte, falls man sich nicht mehr erinnert, was in der Spalte stand.

**Comment by JuliaH1** [comment]
Ihr könnt ja mal gucken, ob das ok so ist. Meiner Meinung nach ist es fertig, schließe erstmal den Issue.

**Comment by Nullmann** [comment]
Wenn ein Zeile nicht alle Felder ausgefüllt hat, wird dort auch nichts angezeigt.
![screenshot 2016-02-18 22 02 31](https://cloud.githubusercontent.com/assets/15816473/13158053/6158eec2-d68b-11e5-909c-81a2122c75ee.png)
