### ISSUE TITLE
Schritt 3: Summe als Default bei number

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#148]
Beim Gruppieren könnte bei number-Feldern die Funktion Summe als Default verwendet werden, da das vermutlich der häufigste Anwendungsfall ist.

**Comment by Nullmann** [comment]
Ein Einfaches Austauchen der Befehle verhält sich merkwürdig - dann ist nichts, also eine leere Zeile, preselected @SteffenPegenau 
![befehle](https://cloud.githubusercontent.com/assets/15816473/13174210/6a5c4628-d702-11e5-8e49-939c5857435f.png)

Dies könnte im direkten Zusammenhang mit Issue #144 stehen.

**Comment by SteffenPegenau** [comment]
Die Befehle werden über ng-repeat bzw. ng-options aus dem genannten Objekt geholt. Am einfachsten und schnellsten ist es vielleicht alle Operationen fest einzucoden.

**Comment by Nullmann** [comment]
Vergessen ist immer noch die default-Operation, obwohl es in der Select-List an zweiter Stelle steht.

**Comment by Nullmann** [comment]
Dadurch, dass mit Issue #194 das vergessen raus genommen wurde, ist der Standardwert bei der Aggregation auch wieder "nichts"

**Comment by SteffenPegenau** [comment]
Inzwischen geschlossen.

**Comment by marcusdeem** [comment]
Also bei mir ist Vergessen als Default eingeblendet...

**Comment by marcusdeem** [comment]
Retest erfolgreich ==> Closed
