### ISSUE TITLE
Schritt 2: Verbindungen - keine Zahlen

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#151]
Man sieht die kleinen Zahlen an den Schiebereglern, aber bei den Überschriften "Min:", "Max:" und "Durchschnitt:" fehlen sie.

**Comment by Nullmann** [comment]
Die Verbindungsfelder sind zu diesem Zeitpunkt nicht implementiert und die Templates dafür werden nicht mehr angezeigt (auskommentiert)
