### ISSUE TITLE
Fehlermeldung anpassen

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#152]
Ich habe im 5. Schritt eine Dimension vergessen. Es kommt dann eine Fehlermeldung, die lautet "Schritt 4: ..." - bitte 4 in 5 ändern.
Daneben finde ich die Überschrift der Fehlermeldung etwas merkwürdig:
"Unter datacity.pegenau.com wird Folgendes angezeigt:"

**Comment by Nullmann** [comment]
Das erste wurde in der aktuellen Version bereits mit Commit e1c1744a54d9a873ae3290ee620dc16f36cfdb4f behoben.
