### ISSUE TITLE
Verbindungen nutzen / nicht nutzen funktioniert nicht

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#154]
Egal ob man "Verbindungen nutzen" anklickt oder nicht, werden sie angezeigt.
![gg](https://cloud.githubusercontent.com/assets/15839253/13174325/3946f47e-d703-11e5-94b1-31a0334ce93d.png)

**Comment by Nullmann** [comment]
Welche Ansichtseinstellungen hast du denn gewählt? Name der Collection und der Ansicht helfen hier.

**Comment by JuliaH1** [comment]
Sowohl CollName als auch ImportVersuchMitVerbindungen und da jeweils die unterste Ansicht in der Liste. Ich habe einige Kombinationen der Einstellungen vorgenommen, immer das gleiche.

**Comment by Nullmann** [comment]
die Variable "useConnections" wird von unserer Seite korrekt an's WebGL weiter gegeben. Wird vermutlich an den momentanen Änderungen von Issue #146 liegen.
