### ISSUE TITLE
[2] Straßen breiter

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#155]
Linienbreite etwas erhöhen

**Comment by SteffenPegenau** [comment]
Müsste realisiert werden, indem mehr Straßen parallel gezeichnet werden => schlecht für Performanz

Andererseits: Will man Performanz lassen sich Regenbögen wählen

@Nullmann  prüft, ob er es in der gegebenen Zeit umsetzen kann.

**Comment by Nullmann** [comment]
Zu beachten:
Wenn Straßen horizontal verlaufen, ob oder unten ein Pixel mehr
Wen sie vertikal verlaufen, rechts oder links ein Pixel mehr

**Comment by marcusdeem** [comment]
Ist die Änderung schon auf dem Server? Ich finde, dass die Straßen immer noch sehr dünn (1 px?) aussehen... (Meine Ansicht auf SG57)

**Comment by Nullmann** [comment]
Nein, sind sie noch nicht. Die Optik hier wurde erstmal nach hinten verschoben, da man hier mehrere Linien zeichnen und berechnen müsste, welche zu Lasten der Performance gehen würde.

**Comment by marcusdeem** [comment]
PAsst jetzt
