### ISSUE TITLE
Warum gibt es keine Straßen?

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#157]
Bei Testansicht Marcus 1 und 2 schaffe ich es nicht, die Straßen zu sehen, obwohl ich denke, alles nötige ausgewählt zu haben. Wo liegt der Fehler? (User oder System?)

**Comment by Nullmann** [comment]
Der Fehler liegt vermutlich am System; habe ich vorhin selbst festgestellt. Problem wird vermutlich das gleiche sein wie #154 und ist wahrscheinlich behoben, wenn Issue #146 bearbeitet wurde.

**Comment by Nullmann** [comment]
Der Fehler lag halb im System, halb in der Bedienung. 
Das Problem liegt darin, dass einmal die Aggregation ausgewählt wurde. Wenn aggregiert wird, können keine Verbindungen angezeigt werden (keine eindeutigen Bezeichner für die Gebäude).
Die Option war zwar in der Oberfläche ausgeschaltet, aber war im Hintergrund noch gesetzt.

**Comment by Nullmann** [comment]
Ich habe in Ihrer Ansicht "Testansicht Marcus 1" die Dimension "Namen" auf "Package" gestellt - so werden die Verbindungen angezeigt.

Könnten Sie das überprüfen?

**Comment by marcusdeem** [comment]
Ja, funzt jetzt.
