### ISSUE TITLE
[1] Import Funktion

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#158]
Warum ist die Import Funktion ein eigenes Tool und nicht eine Funktion im Client?

**Comment by Nullmann** [comment]
Wir hatten uns damals für die Import-Funktion als eigenes Tool entschieden, weil die Datenmengen die Upload-Funktionen über den Browser vermutlich übersteigen würden (Der 8 Mio Datensatz besitzt 250 MB).

**Comment by marcusdeem** [comment]
Könnten Sie es bitte dennoch als Funktion in den Client einbauen - dann eben mit Hinweis, dass nur files bis xxx hochladbar sind? Das fände ich deutlich angenehmer im Handling, als dann immer eine weitere Anwendung öffnen zu müssen...

**Comment by Nullmann** [comment]
Zu Prüfen ist:
Ist es möglich, über den Browser den Import (Der Rohdatei) auf die MongoDB zu realisieren und dann dort Server-Seitig das import-Skript auszuführen?

**Comment by SteffenPegenau** [comment]
Spontan fallen mir zwei grundsätzlich verschiedene Möglichkeiten ein, so etwas umzusetzen:

### Über den Browser:
- CSV-Datei wird ausgewählt oder in Bereich gezogen
- CSV-Datei wird lokal vom Browser zu JSON geparst, beispielsweise damit: http://papaparse.com/
- Objekt wird über RESTHeart an Server geschickt:
*PUT* /db/neueCollection
- Auf dem Server wird ein Trigger ausgelöst, der im günstigsten Fall einfach den *grunt metadata*-Task aufruft.
@ZiZiWang 
Bitte prüfen, wie wir den Trigger umsetzen könnten.

### Über eine Batch-Datei
Man zieht per Drag 'n Drop die zu importierende CSV-Datei auf eine Batchdatei. Die startet den Import über **grunt import**.

Die zweite Variante wäre weit weniger cool, ist dafür aber wahrscheinlich in < 1 Stunde implementiert...

**Comment by ZiZiWang** [comment]
Import über eine Batch-Datei wurde tatsächlich in aktuellem WindowsPaket realisiert, obwohl die Datei nicht per Drag and Drop sondern durch das Eingeben des gewünschten importierten Datei Name importiert wird. Ich versuch noch, wie man die Datei über den Browser impotiert.

**Comment by ZiZiWang** [comment]
mongoDB unterstützt die Trigger-Funktion wie SQL Datenbank **nicht**. Es gibt ein Nodejs Lösungskonzept für die Umsetzung des Triggers in mongodb(https://www.npmjs.com/package/mongo-triggers). Aber bei diesem mongo-trigger wurden nur die Änderungen der Dantensätzen innerhalb einer Collection beobachtet. Die Überwachung der createCollection() Funktion wurde noch nicht hinzufügt. 
Und ich dachte, durch  PUT <dbname>/<collectionname> nur eine leere Collection ohne Datensätze erzeugt wird. Direkter Import von geparsten JSON Daten kann nicht durch Restheart realisiert.

**Comment by ManuelMueller1988** [comment]
Hallo Herr Deem, Tests unsererseits erfolgreich. Kann in meinen Augen daher geschlossen werden.

**Comment by marcusdeem** [comment]
yep, funktioniert, closed
