### ISSUE TITLE
WebGL: Weniger Lichtquellen

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#159]
Könnte man die WebGL-Performance durch Reduktion der Lichtquellen reduzieren?

Vorschlag von AL

**Comment by Nullmann** [comment]
Hab ich gerade ausprobiert, indem ich der gui.js ein paar Lichtquellen auskommentiert habe:
```
function setLight(scene) {
    // Licht hinzufügen. AmbientLight ist generell das Licht auf die Scene auf alles
    scene.add(new THREE.AmbientLight(0x444444));

/*
    //Weiteres Licht, legt Farbe und Intensität fest mit den Arugmenten
    var light1 = new THREE.DirectionalLight(0x999999, 0.9);
    //Einmal das Licht von rechts oben vorne
    light1.position.set(1, 1, 1).normalize();
    scene.add(light1);

    // Einmal Licht von links oben hinten
    var light2 = new THREE.DirectionalLight(0x999999, 1.5);
    light2.position.set(1, 1, -1);
    scene.add(light2);
    */
}
```

Die Performance habe ich nicht getesetet, bin mir allerdings nicht sicher, ob das Ergebnis überhaupt noch akzeptabel ist, selbst wenn es die Performance verbessern würde:

![weniger lichter 2](https://cloud.githubusercontent.com/assets/15816473/13184802/38c295e0-d73e-11e5-90ba-e296eb88831b.png)

**Comment by SteffenPegenau** [comment]
Und wenn nur ein Licht auskommentiert und das andere heller gemacht wird (oder so...)?

**Comment by SteffenPegenau** [comment]
Wurde in der Gruppendiskussion für inakzeptabel befunden.
