### ISSUE TITLE
WebGL: Anderes Material für Gebäude

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#160]
Könnte man das Material der Gebäude anpassen, um die Performance zu verbessern?

Vorschlag von AL

**Comment by Nullmann** [comment]
Was ist denn genau mir anderem Material gemeint?

**Comment by SteffenPegenau** [comment]
Das Material kommt aus der Datei
https://github.com/Data-City/client/blob/master/app/scripts/libs/webgl/gui.js

und wird wohl über den folgenden Code-Schnipsel umgesetzt. Es könnte sein, dass es Materialien gibt die generell sparsamer sind (als MeshPhong) oder dass einige Parameter ungünstig gewählt sind
```
/**
 *Hilfsmethode, um ein schönes Material zu bekommen, wenn man die Farbe kriegt
 *@param: aColor: eine Farbe, i.A. als Hexa-Wert, aber als RGB auch moeglich, oder mit "new THREE.color(0,0,1)"
 *@return: das Material in der gewuenschten Farbe
 */
function getMaterial(aColor) {
    return new THREE.MeshPhongMaterial({
        color: aColor,
        //specular: 0x333333,
        //shininess: 50,
        side: THREE.DoubleSide,
        vertexColors: THREE.VertexColors,
        shading: THREE.SmoothShading
    });
}
```

**Comment by JuliaH1** [comment]
Beide Material Änderungen haben zu keiner Verbesserung geführt. Weder beim unabhängigen Testen, noch beim gemeinsamen prüfen von FlatShading und FrontSide
