### ISSUE TITLE
WebGL: Navigation in Stadtansicht

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#161]
Da man beim Navigieren durch die Stadt leicht versehentlich den Fixpunkt verschiebt, wäre es cool, wenn die Pfeiltasten (tatsächliche auf Tastatur oder ggf. eingeblendete im Display) zur Verfügung stünden, um die aktuelle Sicht entlang einer Achse zu verschieben.

Vorschlag von AL

**Comment by Nullmann** [comment]
Reicht der Punkt "Anfangsansicht", der den Fixpunkt wieder in die Mitte rückt, nicht?

**Comment by SteffenPegenau** [comment]
Nein. Die Steuerung durch die Stadt ist mit der Maus etwas hakelig. Es passiert nicht immer das, was man erreichen will. Dann versucht man die Perspektive zu retten und alles wird nur noch schlimmer... :confounded:

Wenn man mit Tasten entlang einer Achse fahren könnte, wäre die Bedienung leichter.

Heute besprochenes Szenario:
Man will sich in der Vogelperspektive die Verbindungen anzeigen lassen, indem man parallel zur Stadtebene darüber fliegt. Das gelingt mit der Maus kaum. Eine Bedienung mit Pfeiltasten wäre einfacher und intuitiver.

**Comment by thuylinhluu** [comment]
Man kann den Fixpunkt perfekt auf ein Gebäude richten, wenn man dafür die Gebäudesuche benutzt. Damit wird der Fixpunkt nämlich automatisch auf das entsprechende Gebäude gesetzt.

Aber ich kann mir vorstellen, dass die Bedienung nicht so leicht ist. Da ich mich hierfür auch reinarbeiten müsste und man vermutlich eine der threej.js-Dateien kleines bisschen umschreiben müsste, die ich mir noch nie richtig vergeknöpft habe, könnte sich da jemand anderes darum kümmern.

**Comment by Nullmann** [comment]
Die Navigation mit den Pfeiltasten bietet nur mit der linken und rechten Maustaste eine dritte Option die Ansicht zu verändern.
Ist da noch mehr gewollt? Ist das richtig so? Was genau soll hier noch gemacht werden?

**Comment by Nullmann** [comment]
Navigation soll bei einer Vogelperspektive parallel zur Ebene verschoben werden
