### ISSUE TITLE
WebGL: Vogelperspektive verbessern

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#166]
Wenn die Vogelperspektive gewählt wird, sollte die Höhe aller Gebäude auf 0 gesetzt werden.

Vorschlag von AL

**Comment by Nullmann** [comment]
Einfacher zu implementieren: Bei Auswahl der Vogelperspektive wird die Höhe logarithmiert.

**Comment by thuylinhluu** [comment]
Ist das klar durchdacht? Es war nach einer 3D-Ansicht gefragt. Wenn ich die Höhe aller Gebäude auf 0 setze und der Nutzer den Drehwinkel ändert, dann ist das doch irgendwie blöd?

Umsetzung wäre: einmal durch den ganzen Datensatz iterieren und alle Gebäude skalieren. Wenn der Nutzer fertig wäre mit der Vogelperspektive, dann wird noch einmal durch den ganzen Datensatz iteriert (welcher ja am besten 1 Mio groß sein sollte....) iteriert, um alle Gebäude darzustellen.

Ich glaube nicht, dass das eine Option ist - meine Meinung.

**Comment by Nullmann** [comment]
Da ich das auch als wenig sinnig ansehe, habe ich dafür einen neuen issue #167 mit einem relativ einfachem Verbesserungsvorschlag erstellt.
