### ISSUE TITLE
Immer, wenn Nutzer P ins Textfeld eingibt, wird ein Screenshot gemacht

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#172]
Man soll ja "die erste Zeile der CSV-Datei" in der Legende ändern können. Wenn der Nutzer nun "Package" eingeben möchte, wird ein Screenshot gemacht. Das P wird auch geschrieben. Man könnte überlegen, ob man die Screenshot-Funktion nicht mit einer Kombination von Tasten machen möchte... oder es einfach so lässt wie es ist

**Comment by Nullmann** [comment]
Hab die Funktion jetzt auf die Taste "Entfernen" gelegt... eine geeignete Taste zu finden, die in der ASCII-Tabelle zu finden ist und nicht mit Textbearbeitung zu tun hat (Shift, Tab, ...) ist echt schwer.
