### ISSUE TITLE
Fehlermeldung, wenn keine Dimension im ersten Schritt genutzt wird

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#173]
Die Fehlermeldung erscheint, dass in Schritt fünf keine Dimensionen gewählt sind, jedoch fände ich eine Fehlermeldung besser wie: "Sie haben in Schritt 1 keine Dimensionen/Attribute ausgewählt", weil der Fehler ja nicht in Schritt 5 liegt, sondern in schritt 1.

Und wenn nur Strings als Dimensionen gewählt wurden, kann man logischerweise für die Dimensionen Höhe,Breite und Farbe nichts auswählen, was beim klicken auf Stadt anzeigen auch zur Fehlermeldung "In Schritt fünf keine Dimensionen ausgewählt" führt. Fände hier eine Fehlermeldung gut, die sagt, dass nur Strings im ersten Schritt gewählt wurden und dass somit keine Stadt generiert werden kann

**Comment by Nullmann** [comment]
Naja, aber der Fehler liegt doch darin, dass im 5. Schritt keine Dimension ausgewählt wurde. Das ist der prominente Eingabefehler.

Ich würde als einfache Lösung einfach noch hinzufügen: "(Gegebenenfalls wurde in Schritt 1 zu viel heraus gefiltert)". Reicht dir das?
Ansonsten kann das ja auch ins Benutzerhandbuch.

**Comment by Nullmann** [comment]
Habe es nun wie oben beschrieben umgesetzt. Reicht das für dich?

**Comment by JuliaH1** [comment]
Ja, ich denke, das reicht
