### ISSUE TITLE
Keine Daten in der gefilterten Form

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#175]
Wenn der Filter so eingestellt ist, dass kein Datensatz darauf passt, dann arbeitet und arbeitet er und es tut sich nichts. Am besten das durch eine Fehlermeldung abfangen, dass keine Daten auf die gewählte Filterung passen

**Comment by Nullmann** [comment]
Welche Collection und welche Ansicht hattest du zu dem Zeitpunkt ausgewählt? Damit ich mir genauer anschauen kann, ob das leicht abzufangen ist (denke schon)

**Comment by JuliaH1** [comment]
Man sieht es jetzt unter Collection Test, Ansicht Julia. Habe die Filter so gesetzt, dass keine Daten drauf passen
