### ISSUE TITLE
Manchmal grün, manchmal nicht

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#177]
Wenn ein Vorgarten angeklickt wird, dann färbt sich das dazugehörige Gebäude manchmal grün und manchmal bleibt es in seiner Farbe. Ich konnte aber leider noch kein Muster erkennen, wann was passiert... Kommt mir irgendwie vor, dass das schon mal angesprochen wurde oder?

**Comment by ManuelMueller1988** [comment]
Das liegt an folgender Situation: Haus A und Haus B haben Verbindungen zu Haus C. Beide aktivierte Verbindungen färben das Gebäude grün (Verbindung A-C färbt C grün, danach aktivierte Verbindung B-C lässt C grün), wenn jetzt eine der beiden Verbindungen deaktiviert wird, wird auch die Färbung des Gebäudes entfernt, auch wenn die andere Verbindung noch besteht... man müsste also pro Gebäude erst die Farbe löschen wenn keine eingehende Verbindung mehr aktiv ist.
