### ISSUE TITLE
Differenzierte Ladeanzeige beim Aufbau der Stadt

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#180]
Gerade wenn es länger dauert die Stadt aufzubauen, ist eine differenzierte Ladeanzeige wichtig.

Es **könnte** angezeigt werden:
- Erzeuge Gebäude
- Verschiebe Gebäude
- 50 %

**Comment by Nullmann** [comment]
Vorschlag: Information in dem div-Element ausgeben, wie weit er beim Laden ist. Konsolen-mäßig.

**Comment by Nullmann** [comment]
Das div-Objekt wird erst aktualisiert, wenn die komplette Stadt schon gebaut ist..

**Comment by Nullmann** [comment]
Es gibt auch eine Bootstrap-Eigene Ladeanzeige:
http://getbootstrap.com/components/#progress-basic

**Comment by SteffenPegenau** [comment]
Könnte mit 613ff25 erledigt sein. Bitte mit (IE) testen und ggf. schließen.

**Comment by Nullmann** [comment]
Klappt und sieht schön aus. Da die eigentliche Funktionalität des Balkens bereits ausführlich getestet wurde, schließe ich den Issue.
