### ISSUE TITLE
Performance nimmt mit Laufzeit ab

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#181]
Testen für wenige Minuten bringt das leider nicht ans Tageslicht. Je länger die Stadt offen bleibt, desto "ruckeliger" wird es, sodass selbst kleine Städte nach gewisser Zeit (bspw. man lässt es in einem Tab 30min offen und will es dann wieder benutzen) nicht mehr zu handhaben sind.

**Comment by SteffenPegenau** [comment]
@thuylinhluu @Nullmann 
Könnte das mit der mal angesprochenen Rekursionstiefe zusammen hängen? Bug?

**Comment by Nullmann** [comment]
Das hört sich zumindest ziemlich stark nach einem Memory Leak an. Also könnte es sein, dass da ein Rekurionsanker falsch gesetzt ist.

**Comment by SteffenPegenau** [comment]
Das Problem ließ sich mit neuer Dist nicht mehr reproduzieren.
