### ISSUE TITLE
Verkürzter Horizont

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#183]
Ab 50.000 Datensätze stellt bei mir der IE keine Stadt auf Dauer dar. Das heißt, es lädt erst lang, und nachdem die Stadt kurz dargestellt wird, wird WebGL kurz schwarz und zeigt dann nur noch das Drop-Down Menü an und den Hintergrund ohne Stadt. So sieht das aus...
![ie](https://cloud.githubusercontent.com/assets/15839253/13252318/534b23aa-da36-11e5-804c-551e876e6e04.png)

Beim Firefox wird eine Warnung (Nach etwa 20sec)  angezeigt des nicht antwortenden Skripts. Man muss dann auf Skript fortsetzen (oder so ähnlich) klicken, damit es weiter geht. Danach wird dann die ganze Stadt (50.000) dargestellt, ohne dass sie verschwindet. 
Was aufgefallen ist, je näher man an die Stadt ranscrollt, umso besser ist das Handling bzw. die Perfomance. Bis hier hin etwa ist die Darstellung perfekt und flüssig...
![blablba](https://cloud.githubusercontent.com/assets/15839253/13252473/284637e8-da37-11e5-94cc-8b9bff3224ab.png)
Dabei habe ich mich daran erinnert, dass André eine "verkürzten Horizont" vorgeschlagen hat. Das heißt, wir haben eine fixe Größe der Darstellungsfläche und es werden nur die Gebäude angezeigt, die man maximal betrachten kann, ohne dass es ruckelt. Den Rest der Stadt kann man nicht sehen, da er sozusagen hinterm "Horizont" ist. Mit dem Verschieben der Stadt fallen auf der einen Seite der Stadt die Gebäude weg und auf der anderen Seite erscheinen dann die, die man angezeigt haben möchte.

**Comment by thuylinhluu** [comment]
Du kannst hier für die Performance mit dem "verkürzten Horizont" das mal selbst ausprobieren. Gehe dazu in ClientWebGL.js in Zeile 396.
" camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 10000);"
Die Zahl 10000 sagt, bis wohin die Kamera "sieht", also wie weit die Objekte entfernt sein dürfen, dass sie noch gezeichnet werden.

**Comment by SteffenPegenau** [comment]
Der verkürzte Horizont hat zwei Makel:
- Der Horizont verläuft mitten durch die Stadt => Die Optik zerreißt, was nach Grafikfehler aussieht
- er lässt sich nicht mit dem grundsätzlichen Ziel "Übersichtlichkeit" vereinbaren.
