### ISSUE TITLE
Skalierung - Stadt aktualisiert

### ISSUE THREAD

**Issue by aloske** [Data-City/client#184]
Ich habe gerad zufällig einen Bug(?) entdeckt:
1. Stadtansicht skaliert (z.B. Höhe log.)
2. Stadt aktualisiert (z.B. Verbindungen eingeschaltet)
3. Neue Stadt wird nicht log gezeichnet obwohl log noch ausgewählt ist. Wenn man den Haken dann entfernt verschwindet die ganze Stadt.

**Comment by Nullmann** [comment]
Habe dafür einen neuen Issue erstellt - #186

**Comment by thuylinhluu** [comment]
Es ist schon eher ein Bug. Die Einstellungen sollten eigentlich bereits resetted sein. Da ist ein Fehler entstanden, weil die gui oder genauer das Dropdownmenü nicht neu erstellt wird, sondern das alte verwendet wird. Das sollte man ändern.

**Comment by Nullmann** [comment]
Sollte ich behoben haben. Bitte überprüfen, ob das nun so richtig ist.

**Comment by thuylinhluu** [comment]
Könnte sein, dass, wenn die Legende geändert wurde, Gebäudeinformationen angezeigt wurden, Zoomgeschwindigkeit etc. (d.h. alle anderen Sachen im dropdownmenü) dabei nicht aktualisiert worden sind. Schau da doch bitte nochmal nach

**Comment by aloske** [comment]
Konnte den Fehler auch nicht mehr reproduzieren. Danke!

**Comment by marcusdeem** [comment]
Also bei mir kommt der Fehler noch in Marcus Testansicht 1 - Stand anzeigen, Höhe und Breite logarithmieren, dann sieht es gut aus. Dann Verbindungen von Straßen auf Regenbögen umstellen und Stadt aktualisieren, dann sind die Gebäude wieder unlogarithmiert dargestellt, obwohl beide Haken noch gesetzt sind...

**Comment by marcusdeem** [comment]
So ganz entspricht das Verhalten noch nicht meinen Erwartungen:
Ich logarithmiere, ändere dann bspw. Verbindungen und aktualisiere dann die Stadt.
Jetzt ist es so, dass die Logarithmierung wieder weg ist (und immerhin konsistent auch das Häkchen im Menü nicht mehr da ist).
Ich hätte es aber eigentlich eher erwartet, dass die Logarithmierung nach wie vor im Menu markiert ist und auch angewendet wird.

**Comment by Nullmann** [comment]
Da es hier ursprünglich um ein anderes Thema ging, schließe ich den Issue und habe einen konkreteren Issue #214 dafür geöffnet, wo dann dieses neue Feature besrochen wird.
