### ISSUE TITLE
Alle Einstellungen resetten, wenn eine neue Stadt gezeichnet wird

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#186]
Ist in der init wohl am besten aufgehoben.

**Comment by thuylinhluu** [comment]
Hm ich glaube, dass dieser Issue nicht dasgleiche ist wie Issue #186. Es ist schon eher ein Bug. Die Einstellungen sollten eigentlich bereits resetted sein. Da ist ein Fehler entstanden, weil die gui nicht neu erstellt wird, sondern die alte verwendet wird. Das sollte man ändern.

**Comment by JuliaH1** [comment]
DropBox wird immer gelöscht und neu gezeichnet

**Comment by JuliaH1** [comment]
keine DropBox sondern Drop Down-Menü

**Comment by marcusdeem** [comment]
Ich glaube, dieser Issue meint einen Fehler, den ich auch sehe - wenn ich logarithmieren wähle, und danach von Straßen auf Regenbögen wechsle, wird die Stadt nicht mehr logarithmiert dargestellt, aber die Checkboxes sind immer noch mit Häkchen versehen

**Comment by Nullmann** [comment]
Sollte behoben sein.
Weiteres Besprechen dann bitte in #184
