### ISSUE TITLE
Dimensionswahl: Name -> ID

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#188]
Bezeichnung der Dimension ändern: Name -> ID

Außerdem: Hinweis in Doku, zu welchen Problemen es kommt, wenn ID nicht eindeutig ist

**Comment by Nullmann** [comment]
Wurde mit ac37caea20e008ef229149bb441daa231dcf2fa9 erledigt

Wenn Hinweis in Doku gemacht wurde, kann der Issue geschlossen werden

**Comment by MarcelMP** [comment]
Hinweis wurde bei der Dimensionswahl und bei der Gebäudesuche im Benutzerhandbuch vermerkt.
