### ISSUE TITLE
Ausgangspunkt der Regenbögen

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#189]
Kosmetik:
Die Regenbögen beginnen/enden an der Spitze des Pfeils. Schöner sähe aus, wenn sie in der Mitte (also geometrisch formuliert: im Schwerpunkt) des Dreiecks beginnen/enden würden.

**Comment by Nullmann** [comment]
Die Ausgangspunkte wurden zentriert, sind aber variabel auf einer Linie (Wird bei jedem Anklicken neu berechnet). Dies ist nötig, damit nicht alle Verbindungen von einem Punkt aus verlaufen.
Ist das Ihnen so Recht?

**Comment by marcusdeem** [comment]
In "Benedikts Testansicht" beginnen die Regenbögen immer noch an der Spitze der Pfeile...

**Comment by ManuelMueller1988** [comment]
![2016_03_02_16_47_37_datacity_internet_explorer](https://cloud.githubusercontent.com/assets/15968962/13465875/c6db5f1c-e097-11e5-9d34-8c0b11aeb769.png)

**Comment by Nullmann** [comment]
Genau so soll das auch sein. Damit sich die einzelnen Verbindungen nicht in einem Punkt des Dreiecks clustern. Allerdings bewegen sie sich lediglich auf einer Linie parallel zum Gebäude, in der Hälfte der Höhe des Dreiecks.

**Comment by SteffenPegenau** [comment]
Sieht in für mich irgendwie kaputt aus. Die Unterscheidung im Ausgangspunkt ist in meinen Augen nicht so wichtig. Wäre dafür alle Linien aus einem Punkt kommen zu lassen. Was sagen die anderen?

**Comment by JuliaH1** [comment]
Bin auch dafür, dass alle Verbindungen in einem Punkt enden sollen. Man kann daraus nämlich keine zusätzliche Information ziehen, wenn sie nicht geclustert werden. Die einzige Information, die man hier hat, ist, dass Verbindung X von Gebäude A nach Gebäude B geht, und dafür müssen die Linien nicht aufgeteilt werden sondern können geclustert bleiben

**Comment by marcusdeem** [comment]
Sieht gut aus
