### ISSUE TITLE
[Optik] Gebäudeinformation schlecht lesbar

### ISSUE THREAD

**Issue by marcusdeem** [Data-City/client#190]
Leider noch einer. Hat was von Kosmetik, finde ich aber doch wichtig:
Bei den Gebäudeinformationen ist die Schrift zu weit unten in den TextBoxen, dadurch kann man das nicht gut lesen.
Wünschenswert wäre, die Schrift vertikal zu zentrieren.

**Comment by Nullmann** [comment]
Dies ist anscheinend nur im Internet Explorer so. Hier der Vergleich:
Firefox:
![schrift ff](https://cloud.githubusercontent.com/assets/15816473/13360060/80a0d79a-dcb7-11e5-8849-26d6fbb1a5ce.png)
Internet Explorer:
![schrift ie](https://cloud.githubusercontent.com/assets/15816473/13360062/8309d28e-dcb7-11e5-9309-0d1b74d02a71.png)

**Comment by Nullmann** [comment]
Interessanterweise lässt sich dies lösen, wenn man einmal drauf klickt.

Habe aber auch ein mit Internet Explorer funktionierendes Beispiel gefunden:
http://workshop.chromeexperiments.com/

Kanna bisher aber nicht herausfinden, wieso das bei uns so verschoben ist.

**Comment by ManuelMueller1988** [comment]
Vermutlich: Über CSS lösbar

**Comment by Nullmann** [comment]
Wird auch im IE schön dargestellt.
