### ISSUE TITLE
"Vergessen" rausnehmen, wenn gefiltert wurde

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#194]
Die Filterung vom Datensatz macht nur Sinn, wenn man ihn beim dritten Schritt (Aggregierung) nicht auf "Vergessen" setzt. Denn sonst fliegt die Filterung raus. Bspw beim großen Datensatz, wenn man die ID's filtert und auf 500 setzt, aber bei der Aggregierung nach bspw gender den Wert von ID auf "vergessen" setzt, werden trotzdem 10.000 angezeigt, obwohl man hier nur 500 angezeigt haben möchte

**Comment by SteffenPegenau** [comment]
Die Änderung habe ich revidiert. Konnte das Problem nicht nachstellen bzw. funktioniert es so wie es sollte:
- Ich stelle beim BigData-Datensatz ID bis maximal 2 ein
- Ich gruppiere über Länder
- Es werden zwei Gebäude angezeigt mit verschiedenen Ländern angezeigt
