### ISSUE TITLE
Tabellen sortieren

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#199]
Die Tabellen (Collections & Ansichten) sollten entweder nach letzter Änderung sortiert sein oder frei sortierbar sein. Die Sortierfunktion lässt sich beispielsweise damit umsetzen: http://ng-table.com/

(Geringe Prio)

Wenn erledigt bitte von AL prüfen und schließen lassen.

**Comment by SteffenPegenau** [comment]
Mit Angular-Bordmitteln für die Tabelle der Ansichten mit 9f83780 umgesetzt.

@aloske
Passt das so?

**Comment by ManuelMueller1988** [comment]
Funktioniert. Kann geschlossen werden.

**Comment by Nullmann** [comment]
Hab's auch nochmal mit dem IE getestet und schließe das dann mal :D
