### ISSUE TITLE
Button "Ansicht speichern" farblich hervorheben

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#20]
Vielleicht in grün, damit deutlich wird, dass man mitbekommt, dass man speichern muss.

(Bis wir einen Mechanismus eingebaut haben, der den Wechsel verhindert wenn ungesicherte Daten eingetragen sind bzw. nochmal nachfragt, ob man die Änderungen verwerfen will)

**Comment by Nullmann** [comment]
Referenz: http://www.w3schools.com/bootstrap/bootstrap_buttons.asp
