### ISSUE TITLE
[Verbindungen] Verbindungsanzeige von Häusern über Schalter aktivierbar

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#200]
**Problem:** Bei sehr großen Häusern lassen sich die Vorgärten zum Aktivieren der Verbindungen kaum anklicken, weil sie zu klein sind (Vom Kunden war gewünscht, dass alle Gärten die gleiche Größe haben - dieses Problem hatten wir erwartet).

**Lösungsvorschlag:** Die Verbindungsanzeige lässt sich über Buttons in der Legende aktivieren.

**Comment by aloske** [comment]
Die Lösung halte ich für gut. Es müssten allerdings nach Anwahl des Buttons in der Legende zunächst alle Gebäude in der Stadt gehighligtet werden, die auch entsprechende Verbindungen haben. Sonst weiß der Nutzer nicht, welche Gebäude "anklickbar" sind. -> Hier sollten wir Rücksprache mit Herrn Deem halten.

**Comment by ManuelMueller1988** [comment]
Einfügen von drei Buttons in der Legende: 
1. Highlighted Gebäude, die Verbindungen haben
2. Aktiviert eingehende Verbindungen vom markierten Gebäude
3. Aktiviert ausgehende Verbindungen vom markierten Gebäude
(Im Meeting beim Kunden wurde besprochen, dass die Größe der Vorgärten nicht dynamisch angepasst werden soll)

**Comment by JuliaH1** [comment]
Bitte testen und gegebenenfalls schließen

**Comment by Nullmann** [comment]
DIe eigentliche Funktionalität funktioniert, der aufgetrene Bug wurde in Issue #243 weiter konkretisiert
