### ISSUE TITLE
[Optik] (teilautomatische) lineare Skalierung

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#201]
Um Darstellungsfehler zu vermeiden, wären kleinere Gebäude wünschenswert. Evtl lässt sich das erreichen, indem alle Zahlenwerte durch 10 (100, 1000 ... müsste man dynamisch feststellen) geteilt werden.

(Vermutlich eher Backlog)

**Comment by SteffenPegenau** [comment]
@aloske
Die einzelnen Dimensionswerte werden aktuell schon durch den geringsten Wert geteilt, allerdings streuen die Werte im neusten Beispieldatensatz extrem. Würde man zusätzlich durch 10 oder höhere Werte teilen, verschwänden die kleinsten Gebäude.
Man kann die Darstellungsfehler vermeiden, indem man die Filter entsprechend setzt. 
Hast du noch Ideen? Ansonsten würden wir die Idee schließen.

**Comment by aloske** [comment]
Vorschlag: Daten standardisieren

Ansonsten müssen wir eine andere Möglichkeit finden. Diese Darstellungsfehler versauen uns die schönen Ausgaben ...

**Comment by Nullmann** [comment]
Der momentane Datensatz hat eine sehr große Varianz.
Die Spalte "TOTALVERB" reicht von 2 bis 19247. Momentan wird bereits durch das kleinste Gebäude geteilt (hier also durch zwei), um alle Gebäude so klein wie möglich darzustellen. Damit hat das größte Gebäude aber immer noch eine Fläche von knapp 10.000, sodass es zu Kantenflimmern kommt (die Kamera ist zu weit draußen) und die Vorgärten nicht mehr sichtbar sind.

**Comment by Nullmann** [comment]
Eine Möglichkeit dies zu umgehen ist es die FIlter so einzustellen, dass die kleinsten Gebäude größer sind und so durch eine größere Zahl geteilt wird. Dies muss noch mit Issue #203 umgesetzt werden.

**Comment by aloske** [comment]
Vielleicht habe ich es falsch verstanden, aber die kleinen Gebäude rauszufiltern ist hier keine Lösung. Ein häufiges Ziel der Codeanalyse wird es sein, solche kleinen Gebäude zu erkennen.

**Comment by thuylinhluu** [comment]
Was ist denn mit dem Vorschlag "Daten standardisieren" gemeint?

**Comment by Nullmann** [comment]
(Nicht in der Dist!) wird momentan alle Gebäude nicht durch das minimale Gebäude geteilt, sondern durch den Durchschnitt. Dadurch werden große Datensätze in ihrere größe linear und dynamisch an die Straßen und an die Vorgärten angepasst, sodass diese besser sichtbar sind, sodass dies auch die Issues #200 und #155 beheben würde. Dies behebt auch das Kantenflimmern, weil die Kamera nicht so weit weg ist von der Stadt.

Das einzige, was mir gerade (etwas) negativ auffällt: Ein Gebäude kann nicht kleiner als mit der Größe "1" dargestellt werden. Dadurch werden Gebäude "vereinheitlicht". 
Beispiel bei dem jetzigen SG57-Datensatz: Die Spalten "TOTALVERB" besitzt die Eigenschaften  Minimum: 2 / / Durchschnitt: 1740.802 / / Maximum: 19247
In diesem Fall dürften also alle Gebäude zwischen 2 und 1740 in der gleichen Größe dargestellt werden.
Ein Vorteil dieser Darstellung ist allerdings, dass auch diese kleinen Gebäude noch sichtbar sind, wenn auch nicht mehr komplett voneinander zu unterscheiden.

Zum Vergleich zwei Bilder:
![teilung durch avg](https://cloud.githubusercontent.com/assets/15816473/13478904/b34c6306-e0d3-11e5-8de2-0a060ff45300.png)
Mit Teilung durch den Durchschnitt

![teilung durch min](https://cloud.githubusercontent.com/assets/15816473/13478954/fb0412ca-e0d3-11e5-990c-a5c120f25295.png)
Mit Teilung durch das Minimum

**Comment by Nullmann** [comment]
Ich habe hierfür unterhalb der Dimensionsauswahl einen Radio Button hinzugefügt, sodass man zwischen den beiden wechseln kann.
Ist meiner Meinung nach die beste (und einzige?) Lösung. Sollte in der Telko besprochen werden.

**Comment by Nullmann** [comment]
Ich habe die Gärten mal dynamisch zeichnen lassen (siehe unten). Das klappt zwar, ist aber in der Größe mit den Grafikfehlern nicht tragbar. Sowohl die Gärten als auch die Straßen sind kaum zu erkennen.

![screenshot 2016-03-03 12 14 47](https://cloud.githubusercontent.com/assets/15816473/13492680/d307260c-e139-11e5-8c7f-c433e81a34de.png)

**Comment by thuylinhluu** [comment]
Das Flackern könnte man umgehen, wenn man die Höhe von den Böden zueinander und zu den Gebäuden variabel hält, d.h. je weiter die Kamera weg ist, desto weiter sollen die Böden voneinander entfernt sein, damit dieses Flackern nicht mehr auftritt.

Für die Gärten kann man zusätzlich ein Button unter Gebäudeinformationen hinzufügen.

**Comment by ManuelMueller1988** [comment]
Klingt nach einem guten Vorschlag

**Comment by aloske** [comment]
Zusammen mit den Buttons im Menü klingt das nach einer guten Lösung.

Am 05.03.2016 um 14:18 schrieb Manuel <notifications@github.com<mailto:notifications@github.com>>:


Klingt nach einem guten Vorschlag

-

**Comment by Nullmann** [comment]
Zu beachten: Nach den jetzigen Änderungen kann es sein, dass alles etwas schwebt. Allerdings ist auch das Flackern weg. Das Schweben fällt bei schräger Ansicht bzw Vogelperspektive aber kaum bis gar nicht auf und eine Querschnittsansicht ist in meinen Augen kein Use Case.

**Comment by Nullmann** [comment]
Der Issue ist überfüllt und es klappt nun soweit. Bei weiteren Diskussionsbedarf/Fehlern -> Neuer Issue
