### ISSUE TITLE
[Verbindungen] Verbindungen zu Häusern, die heraus gefiltert wurden

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#206]
Beispiel: Filter gesetzt: Es werden nur Häuser mit ID <= 5000 angezeigt. Hat nun ein Haus eine Verbindung zum Haus 5100, wird ein Vorgarten gezeichnet. Klickt man darauf, wird der Vorgarten auch markiert, ohne dass eine Verbindung angezeigt würde. 

Möglicher Fix: Alert anzeigen, dass Haus xy (wegen gesetztem Filter/Aggregation) nicht angezeigt wird.

**Comment by ManuelMueller1988** [comment]
Vorgärten, die zu herausgefilterten Gebäuden führen würden, nicht zeichnen. 
@marcusdeem: Soll ein entsprechender Hinweis erscheinen, dass Vorgärten nicht gezeichnet worden sind?

**Comment by marcusdeem** [comment]
Genau: Vorgärten, die ausschließlich Verbindungen enthalten, die zu herausgefilterten Gebäuden führen, können weggelassen werden. Ein Hinweis ist nicht erforderlich, da sie ja mal da waren und erst gelöscht werden, wenn der Nutzer aktiv das letzte verbundene Haus herausfiltert.

**Comment by Nullmann** [comment]
Funktioniert wie beschrieben.
