### ISSUE TITLE
[Verbindungen] Straßen werden nicht gezeichnet

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#207]

**Comment by ManuelMueller1988** [comment]
In dem "Datensatz SG57.." wurden mir in der neuen Dist Straßen angezeigt. (Anm.: Allerdings musste ich ein, zwei mal auf "Script beenden" gehen, bevor das geschieht).

**Comment by Nullmann** [comment]
Kann ich bestätigen. Wenn ich mich recht erinnere, war "firstNode" undefined.

**Comment by Nullmann** [comment]
Dass nur manche Straßen nich gezeichnter werden, dafür gibt es den neuen Issue #211 
Deshalb kann dieser hier geschlossen werden, der ja drauf abgespielt hat, dass die Stadt ohne Straßen gar nicht dargestellt wurde.
