### ISSUE TITLE
Hinweis: Regenbögen performanter

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#208]
In Oberfläche bei Verbindungsauswahl einen Hinweis einbauen, dass Regenbögen performanter sind.

Wenn man sich die einzelnen Verbindungen anzeigen lassen möchte.

**Comment by aloske** [comment]
Warum ist das eigentlich so? Wenn die Straße einmal erstellt wurde (Dijkstra/A* ist durchgelaufen) sollte es doch eigentlich keinen Unterschied machen?

**Comment by Nullmann** [comment]
Die Regenbögen sind natürlich performanter, weil man dort überhaupt keinen Dijkstra braucht.

Wie genau wurde das hier implementiert, @thuylinhluu ?

**Comment by aloske** [comment]
Das ist mir klar. Ich hatte es so verstanden, dass die gesamte Stadtansicht performanter ist, wenn Regenbögen statt Straßen eingezeichnet sind.

**Comment by Nullmann** [comment]
Achso, stimmt, das kann man auch missverstehen. Habe den Anfangspost verständlicher umformuliert :)

**Comment by ManuelMueller1988** [comment]
Erledigt
