### ISSUE TITLE
[Testing] In Testplan aufnehmen: Unerwarteter Input in CSV-Datei

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#209]
Was passiert, wenn statt einer Zahl
- gar nichts
- ein Wort
- ein Wort mit Sonderzeichen (ß,ä,ü,ö)
- eine Zahl
- eine Kommazahl
- eine Zahl mit Buchstaben (3jf798)
- eine Zahl mit Sonderzeichen
- eine Float-Zahl steht (3.0f oder 3f)
in einer Spalte der CSV-Datei steht, die eigentlich nur Zahlen enthalten sollte

**Comment by Nullmann** [comment]
Weiteres Beispiel: Verhalten bei negativen Zahlen

**Comment by aloske** [comment]
Ich denke, dass es in diesem Zusammenhang auch sinnvoll wäre mit dem Zufallsgenerator in Execl mal eine Reihe von Datensätzen zu erzeugen, die unterschiedliche Charakteristiken aufweisen (unterschiedliche Varianz, ein großes mit ganz viele kleine Gebäude, viele von einem Gebäude ausgehende Verbindungen etc.) und mit Data-City anzeigen zu lassen.

**Comment by JuliaH1** [comment]
**Folgendes wurde an fehlerhaften Eingaben getestet:
Statt einer Zahl:**
Float: Gebäude wird trotzdem gezeichnet mit der Zahl
„Leer“: Gebäude wird trotzdem gezeichnet mit Mindestwert 0
undefined (also letzter Wert ist nicht angegeben): wird mit Mindestwert gezeichnet
String: Slider ist kaputt und Stadt wird nicht gezeichnet
negativ: fehlerhafte Darstellung des Gebäudes 
Kommazahl: Gebäude wird gezeichnet mit Kommazahl
Zahl mit Buchstabe am Ende: Gebäude wird gezeichnet
Zahl mit Buchstabe mitten drin in der Zahl: sieht Zahl vor dem ersten Buchstaben und zeichnet mit dieser Zahl (bspw. bei "4sdf4" sieht er nur die 4 und nimmt die als Zahl)
Zahl mit Buchstabe davor: Stadt wird gezeichnet ohne dieses Gebäude (Slider geht nicht mehr)

**Comment by JuliaH1** [comment]
Das von André genannte Beispiel mit einem sehr großen Datensatz und vielen sehr kleinen wurde getestet, und hat nur richtig funktioniert mit "Mit Minimum skalieren". Mit "Durchschnitt skalieren" haben die Verbindungen nicht mehr funktioniert. Die Vorgärten wurden zwar gezeichnet, aber beim Draufklicken ist nichts passiert. Ich schätze mal das liegt daran, dass die Gebäude so minimal klein sind durch diese Skalierung, sodass die Verbindungen nicht gefunden werden. (im Datensatz Testen)

Deswegen sollte man nochmal darüber diskutieren, wie sinnvoll das Skalieren mit dem Durchschnitt ist. Denn gleichgültig, welcher Datensatz, alle Daten unter dem Durchschnitt werden kleiner als die Grundeinheit und somit am Rechner (fast) gar nicht darstellbar und unbrauchbar.

**Comment by MarcelMP** [comment]
Die fehlerhaften Eingaben wurden in den Testplan aufgenommen.

**Comment by SteffenPegenau** [comment]
Kann man den Issue also schließen?

**Comment by JuliaH1** [comment]
Ja, Kann geschlossen werden
