### ISSUE TITLE
Spiegelnde Oberflächen

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#210]
Ich sehe einen leichten Spiegeleffekt auf Gebäudeoberflächen. Wir sollten das herausnehmen, um zu versuchen noch weiter die Performance steigern, oder?

**Comment by Nullmann** [comment]
Das wurde bereits bei der Performance versucht, hat aber nichts gebracht. Das verwendete Material:
http://threejs.org/docs/#Reference/Materials/MeshPhongMaterial

Ein viel einfachereres, dadurch hässlicheres Material hat keine Verbesserung gebracht:
http://threejs.org/docs/#Reference/Materials/MeshBasicMaterial

Siehe Issue #160

**Comment by thuylinhluu** [comment]
Sehe ich wie Bene. Durch ein hässlichere Gebäude wird die Performance nicht (bemerkbar) besser.

**Comment by ManuelMueller1988** [comment]
Ok, wenn die Eliminierung der Spiegelung keinen Benefit bringt, sollten wir sie drin lassen.
