### ISSUE TITLE
Wenn eine Stadt aktualisiert wird, sollten die Einstellungen von der letzten Stadt übernommen werden

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#214]
Lässt sich ggf. über das bereits vorhandene storedJSON umsetzen? (WebGL-seitig)
Local Storage von Angular? (Client-seitig)

-- Abgeleitet aus #184

**Comment by thuylinhluu** [comment]
Wir reden nur von dem Skalieren oder? Wäre es dann evtl. sinnvoll, eine Checkbox bei der Ansichtsauswahl (bei den 5 Schritten) dafür hinzuzufügen?

**Comment by ManuelMueller1988** [comment]
Ja finde ich auch. Die Einstellungen generell immer zu übernehmen halte ich für riskant, da es bei Anwendungsfall A vielleicht Sinn macht, aber in Anwendungsfall B evtl nicht erwünscht ist.

**Comment by Nullmann** [comment]
Habe es genauer konkretisiert nochmal in einem neuen Issue eröffnet.
