### ISSUE TITLE
[Import] Import ü. Client - IE - Schriften überlappen

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#215]
Im Internet Explorer überlagert der Beschreibungstext den Button "Durchsuchen"

**Comment by JuliaH1** [comment]
![huihihp](https://cloud.githubusercontent.com/assets/15839253/13526823/f6825aa8-e20a-11e5-9e39-90b52966dbaf.png)

**Comment by SteffenPegenau** [comment]
@ManuelMueller1988 
Bitte prüfen und ggf. schließen.

**Comment by ManuelMueller1988** [comment]
Done
