### ISSUE TITLE
[Import] Import ü. Client - IE - Ladebalken zu kurz

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#216]
Bei kleinen Datensätzen ist der Balken bei 100% Fortschritt nur ein paar Millimeter breit.

**Comment by SteffenPegenau** [comment]
@ManuelMueller1988 
Bitte prüfen, ob das Thema mit erfolgreicher Schließung von #217 noch relevant ist und ggf. schließen.

**Comment by ManuelMueller1988** [comment]
Ladebalken entfernen, dafür nur die Prozent?

**Comment by SteffenPegenau** [comment]
Nach Tests durch @JuliaH1 konnte keine Verbesserung erzielt werden.

Daher wird der Punkt, wie von @marcusdeem vorgeschlagen ins Backlog gepackt.

**Comment by Nullmann** [comment]
Dies wurde mit Issue #180 zusammen gelöst.
