### ISSUE TITLE
[Import] Import ü. Client - IE - "Erfolgreich"-Nachricht

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#217]
Nachdem der Import durchgeführt wurde, sollte neben der 100% eine "Erfolgreich"-Nachricht erscheinen, damit man weiß, dass alle Prozesse im Hintergrund abgeschlossen sind.

**Comment by SteffenPegenau** [comment]
@ManuelMueller1988 
Bitte prüfen ob der aktuelle Stand zufriedenstellend ist und ggf. schließen.

**Comment by ManuelMueller1988** [comment]
Done
