### ISSUE TITLE
[Import] Auf Datensätze weiterleiten

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#222]
Nachdem der Import erfolgreich abgeschlossen wurde und die 100% erreicht wurden, wäre es schön, wenn man direkt auf die Vorschau der Datensätze weitergeleitet wird

**Comment by SteffenPegenau** [comment]
Mit einem der letzten Commits kam das folgende Verhalten:
Sobald der Upload abgeschlossen ist, wird eine Erfolgsmeldung und ein Button gezeigt, der zu den Ansichten des Datensatzes führt.

@JuliaH1 
Bitte prüfen, ob das so passt und Issue ggf. schließen.

**Comment by JuliaH1** [comment]
Noch nicht ganz. Was ich mir vorgestellt hatte, war dass man auf die Übersicht aller Datensätze, also die Startseite, weitergeleitet wird. Und der Button sollte, finde ich, erst erscheinen, wenn die 100% erreicht wurden.

**Comment by SteffenPegenau** [comment]
Der Button sollte nun erst erscheinen, wenn 100% erreicht sind.

Ist es nicht wahrscheinlicher, dass man mit dem gerade importierten Datensatz arbeiten (Ansichten anlegen) will? Dann wäre eine Weiterleitung zu der Liste aller Datensätze eher lästig...

**Comment by JuliaH1** [comment]
Ja, sieht jetzt gut aus. Und wohin nun weiter geleitet wird, ist vermutlich Ansichtssache. Man könnte sagen, man möchte weiterhin Datensätze importieren, dann wäre die Startseite sinnvoll. Aber logisch wäre auch, wenn man auf die Ansicht des importierten Datensatzes geführt wird. 

Deswegen wird es geschlossen
