### ISSUE TITLE
[Import] lange Name der (Verbindungs)datei ragt bis in die Erläuterung

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#224]
![sdfsdfsdfsdfd](https://cloud.githubusercontent.com/assets/15839253/13526725/255c12a2-e20a-11e5-905e-4979b8dd87ec.png)
 Und zusätzlich wird "Verbindungsdatei.csv" dick geschrieben, während "Beispieldatei.csv" das nicht tut

**Comment by SteffenPegenau** [comment]
@JuliaH1 
Bitte erneut prüfen und ggf. schließen

**Comment by JuliaH1** [comment]
Ist erledigt
