### ISSUE TITLE
[Import] IE Fehler

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#225]
Wenn man über Internet Explorer etwas importieren will mit dem Namen der Datei, dann bleibt der Import bei 0% stehen und macht nichts. Gibt man einen beliebigen Namen ein, geht es. 
Jedoch ist die Ladeanzeige bisschen kaputt... am Ende kommt aber der Button mit dem weiterleiten auf den Datensatz
![bhlgguzugz](https://cloud.githubusercontent.com/assets/15839253/13526961/e9e5bd8e-e20b-11e5-8a1f-040c776c3452.png)

**Comment by ManuelMueller1988** [comment]
Update:
#216 behandelt Ladebalken. Daher bitte hier nicht weiter darauf eingehen.

Bitte Close bei Gutmeldung von: "Wenn man über Internet Explorer etwas importieren will mit dem Namen der Datei, dann bleibt der Import bei 0% stehen und macht nichts. Gibt man einen beliebigen Namen ein, geht es. "

**Comment by JuliaH1** [comment]
Done, da der Ladebalken in #216  schon aufgenommen ist, und das "Namensproblem" ist gelöst.
