### ISSUE TITLE
[Optik] Es schwebt alles

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#226]
Egal welche Einstellungen man macht, oder gleichgültig welcher Datensatz, die Ebene, die Gebäude schweben... Ich glaube das liegt an der Skalierung? (gerade nur auf IE getestet)
![unbenanasdfnt](https://cloud.githubusercontent.com/assets/15839253/13547852/e5320e92-e2e1-11e5-9cd2-36f1e793f0ec.png)

hier sieht man es vielleicht besser
![unbesdfsdfdfnt](https://cloud.githubusercontent.com/assets/15839253/13547854/ed689158-e2e1-11e5-94f8-74edc671e4f0.png)

**Comment by Nullmann** [comment]
Welche Einstellungen hast du denn genau benutzt? Lokal? Online? Welcher Datensatz? Welche Ansicht...?

Sowohl lokal als auch auf der Webseite funktioniert bei mir ImportVersuchMitVerbindungen -> Benedikts Ansicht

**Comment by JuliaH1** [comment]
Über grunt serve, oberer Datensatz ist kleineTestdatei - Julias Ansicht, unten ist TeamTest.

**Comment by Nullmann** [comment]
Das hängt vermutlich damit zusammen, dass diese Abstände zwischen den Ebenen statisch berechnet werden. Je kleiner die Datensätze sind, desto mehr fällt das auf. Hatte Linh im Issue #201 so beschrieben:

"Das Flackern könnte man umgehen, wenn man die Höhe von den Böden zueinander und zu den Gebäuden variabel hält, d.h. je weiter die Kamera weg ist, desto weiter sollen die Böden voneinander entfernt sein, damit dieses Flackern nicht mehr auftritt."

Liege ich da richtig, @thuylinhluu ?

**Comment by thuylinhluu** [comment]
Gebäude schwebten schon immer, es ist nie wirklich aufgefallen. Aber ich lasse sowas wie Gärten und Straßen auch absichtlich etwas schweben, damit sie nicht am Boden kleben und Flackern.

Aber als ich die Schwebeabstände berechnet habe, bin ich von einer Höhe der Boden von 1.5 Einheiten ausgegangen. Die haben sich durch Zeile 635 (toReturn = parseFloat(metaData["min_" + association[dimString]]) / parseFloat(scalingString);) geändert nach dem Skalieren. Daher fällt es jetzt stärker auf. Ich habs jetzt etwas umgeändert.

**Comment by Nullmann** [comment]
Da der Abstand verkleinert wurde, flackert es bereits bei kleineren Höhen.
Das sollte sich an den Datensatz anpassen.

![flackern](https://cloud.githubusercontent.com/assets/15816473/13553122/d7ed3a58-e37d-11e5-80e3-412e38ce9114.png)

**Comment by ManuelMueller1988** [comment]
Done
