### ISSUE TITLE
[Import] Name der Datei übernehmen, keine Ansicht erstellbar

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#227]
Hat man einen Datensatz importiert und man hat den Namen von der Datei übernommen anstatt einen eigenen anzugeben, wird die Datei zwar vollständig importiert, aber nach dem Weiterleiten lässt sich weder eine Ansicht erstellen, noch passiert was, wenn man auf den importierten Datensatz auf der Startseite klickt... Dann kommt nämlich nur das. Die Datensätze verschwinden und nichts passiert. IE und Firefox (Datensatz FehlerhafteEingaben als Beispiel)
![fehlerdfolaf](https://cloud.githubusercontent.com/assets/15839253/13613133/15dec392-e56b-11e5-8d64-ec8eea4cd3bd.png)

**Comment by ManuelMueller1988** [comment]
Konnte den Fehler reproduzieren. Sonntag war er noch nicht vorhanden.

**Comment by SteffenPegenau** [comment]
Könnt ihr das nochmal testen? Konnte den Fehler gerade nicht reproduzieren (Firefox/Chrome).

**Comment by Nullmann** [comment]
Hat bei mir gerade auch geklappt, mit IE

**Comment by JuliaH1** [comment]
Fehler konnte nicht reproduziert werden, deswegen schließen
