### ISSUE TITLE
"Mit Durschnitt skalieren" 

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#228]
Das von André genannte Beispiel in Issue #209 mit einem sehr großen Datensatz und vielen sehr kleinen wurde getestet, und hat nur richtig funktioniert mit "Mit Minimum skalieren". Mit "Durchschnitt skalieren" haben die Verbindungen nicht mehr funktioniert. Die Vorgärten wurden zwar gezeichnet, aber beim Draufklicken ist nichts passiert. Ich schätze mal das liegt daran, dass die Gebäude so minimal klein sind durch diese Skalierung, sodass die Verbindungen nicht gefunden werden. (im Datensatz Testen)

Deswegen sollte man nochmal darüber diskutieren, wie sinnvoll das Skalieren mit dem Durchschnitt ist. Denn gleichgültig, welcher Datensatz, alle Daten unter dem Durchschnitt werden kleiner als die Grundeinheit und somit am Rechner (fast) gar nicht darstellbar und unbrauchbar.

**Comment by aloske** [comment]
Ich glaube, dass wir einen anderen Weg finden müssen, um die Grafikfehler zu beseitigen. Die Skalierung hat einfach zu viele (negative) Implikationen. Insbesondere verfälscht sie auch das Stadtbild stark.

**Comment by ManuelMueller1988** [comment]
Wird in #201 behandelt
