### ISSUE TITLE
[Optik] R+V und Athene oben-rechts

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#229]
Kleines Impressum?

**Comment by JuliaH1** [comment]
@MarcelMP kann der "Datensätze" Button oben links auch das blau als Hintergrund annehmen und nicht das grau?

**Comment by Nullmann** [comment]
@JuliaH1 Ich habe es etwas anders umgesetzt, finde es so aber schön.

**Comment by SteffenPegenau** [comment]
Habe eben noch einen Vorschlag gepusht:
- Navbar Inhalt zentriert, über ein <div class="container"> um den Inhalt
- Farbe des DataCity-Schriftzugs in RuV-Farbe

Falls es euch vorher besser gefiel, können wir es auch wieder rückgängig machen... :blush:

**Comment by JuliaH1** [comment]
Sieht besser aus, würde ich so lassen. Aber das TUD Logo ist über IE bisschen pixelig. Kann man die Auflösung da bisschen hochdrehen oder ein anderes Bild nehmen, das eine bessere Auflösung hat?

**Comment by ManuelMueller1988** [comment]
Farblich schön. Allerdings finde ich es persönlich etwas befremdlich, dass das TU-Logo so zentral steht und rechts noch so viel Platz frei ist.

**Comment by Nullmann** [comment]
Einvernemliche Verschönerung.
