### ISSUE TITLE
Pfeiltasten

### ISSUE THREAD

**Issue by aloske** [Data-City/client#231]
Ich finde es gut, dass man jetzt mit Pfeiltasten navigieren kann. Mir ist allerdings ein Bug aufgefallen: Wenn man die Ansicht gedreht hat, ändert sich auch die "Logik" der Pfeiltasten (oben = links etc.). Auf diese Weise kann man die Pfeiltasten natürlich nicht mehr sinnvoll verwenden.

**Comment by JuliaH1** [comment]
@thuylinhluu lassen sich die Pfeiltasten unabhängig von der X-Y-Z Achse benutzen? Wenn man nämlich auf den links-Pfeil drückt, soll es immer nach links gehen?

**Comment by thuylinhluu** [comment]
Die Stadt hat bestimmte Ausrichtung und ein festes dreidimensionales Koordinatensystem, um das es sich dreht. Will man allerdings immer nach links, wenn man auf die linke Pfeiltaste klickt, müsste man das neu in Abhängigkeit von der Kameraposition und dem Fixpunkt bestimmen. Ich denke, dass es geht, aber nicht, dass das so flott geht, es sei denn, jemand von den anderen hat gerade eine blendende Idee...

**Comment by Nullmann** [comment]
Diese Funktion wurde eingefügt und so getestet, dass sie die Navigation in der Vogelperspektive erleichtert, um sich dort parallel zu der Stadt-Ebene bewegen zu können.

**Comment by Nullmann** [comment]
Wurde heute abgenickt
