### ISSUE TITLE
Keine Stadtansicht

### ISSUE THREAD

**Issue by aloske** [Data-City/client#232]
Ich habe mir einen Testdatensatz erzeugt (Testdaten10000) und importiert. Es hat zwar fast 20 Minuten gedauert, aber ansonsten gut funktioniert. Daraufhin konnte ich auch ohne Probleme eine Ansicht (Andrés Ansicht) erstellen. Wenn ich mir jetzt die Stadt anschauen möchte, sehe ich diese allerdings nicht. Was ist da los?

**Comment by JuliaH1** [comment]
![test10000](https://cloud.githubusercontent.com/assets/15839253/13670775/1fc61362-e6cc-11e5-88d9-3d2a7145f61f.png)
![test10000sdf](https://cloud.githubusercontent.com/assets/15839253/13670776/1fc934fc-e6cc-11e5-8adb-b04439730e25.png)
Das obere Bild zeigt die Stadt nachdem gedreht, gezoomt und gesucht wurde, zu Beginn wurde mir nämlich auch nichts angezeigt.

Das untere Bild zeigt die Stadt, wenn die Höhe und die Breite skaliert wurde. Das Thema ist aber schon bekannt, dass das hapert #201

**Comment by aloske** [comment]
Weshalb ist die Ansicht ohne Zoom leer? Ich kann das in #201 nicht wiederfinden.

**Comment by JuliaH1** [comment]
Die Ansicht ist nicht leer. Es geht darum, dass die Skalierung noch fehlert (deswegen #201) und man in diesem Fall dadurch die Stadt falsch angezeigt bekommt. Wie gesagt, die Stadt ist da, aber da ist noch irgendwo ein Fehler drin

**Comment by Nullmann** [comment]
Die Skalierung fehltert nicht. Sie funktioniert schon. Das Problem an diesem Datensatz ist, dass Die Varianzen seeehr groß sind.Bei der linearen Skalierung mit dem Minimum wird das kleinste Gebäude auf 1 normiert und alle anderen Gebäude entsprechend angepasst.
Bei der linearen Skalierung mti dem Durchschnitt wird der Durchschnitt als normierte Größe 1 angegeben und alle anderen entsprechend angepasst

Hier:
Bei Andrés Ansicht wurde z.B. "Wert1" als die Fläche (Breite) und die Skalierung mit dem Minimum genommen. Der Maximalwert liegt bei 99996628 und wird durch das Minimum von 1185 geteilt, also hat das größte Gebäude eine Fläche von ca. 84.000x84.000. Bei solchen Größen fallen die Grafikfehler der Ebenen umso stärker auf und in diesem Fall schneidet der Horizont einen großen Teil der Stadt ab.

Abhilfe schaffen hier die anderen Skalierungsoptionen, also die Logarithmischen (verfälschen die Stadt) und die Skalierung durch den Durchschnitt, welche die Stadt (Mit Grafikfehlern, ja...) ordentlich darstellt.

**Comment by Nullmann** [comment]
Durch die Änderungen an Issue #201 sollte das Problem hier gelöst sein. Bitte nochmal selbst prüfen @aloske und dann schließen.

**Comment by ManuelMueller1988** [comment]
Done
