### ISSUE TITLE
Highlighten der Gebäude mit Verbindungen funktioniert nicht.

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#238]
Collection: RuVBeispieldaten
Ansicht: Hightlight Versuch

![highlight bug](https://cloud.githubusercontent.com/assets/15816473/13704474/7696ed1c-e79c-11e5-8725-d655f32a0499.png)

Funktioniert beim SG57-Datensatz

**Comment by JuliaH1** [comment]
@Nullmann bitte nochmal prüfen und gegebenenfalls schließen

**Comment by Nullmann** [comment]
Mir ist auf Anhieb kein Datensatz bzw Ansicht aufgefallen, bei dem das noch nicht funktioniert. Daher closed.
