### ISSUE TITLE
[Verbindungen] Fehler beim Finden eines Pfades 

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#239]
![unbenannt](https://cloud.githubusercontent.com/assets/15839253/13722030/5d705c82-e838-11e5-9e48-098ab932e702.png)
Datensatz RuVBeispieldaten, Ansicht Julia
Wenn man auf dieses Gebäude klickt, werden die Straßen nicht angezeigt (Bögen gehen)

**Comment by Nullmann** [comment]
Der Fehler wurde bereits in issue #221 genannt, schließe diesen hier also.
