### ISSUE TITLE
IE: Website kann nicht aufgerufen werden.

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#241]
datacity.pegenau.com kann nicht aufgerufen werden 
![ie website fehler](https://cloud.githubusercontent.com/assets/15816473/13730700/93a0aa22-e956-11e5-8690-f10a6c2db054.png)

Hängt mit dem neuen Zertifikat zusammen? Mein IE lässt sich nur mit https aufrufen, nicht mit http

**Comment by SteffenPegenau** [comment]
It's not a bug, it's a feature! :grimacing: 

Die Verschlüsselung haben wir abgeschaltet, damit die DataCity auch auf Apple Mobilgeräten funktioniert.

Daher nicht ~~https://~~ sondern **http://**. Damit sollte es funktionieren. Bitte testen und ggf schließen.

**Comment by Nullmann** [comment]
Lässt sich umgehen, wenn man die Seite mit "www.datacity.pegenau.com" aufruft. Bei einem Einfachen "datacity.pegenau.com" forciert der IE die Verschlüsselung mit https.
