### ISSUE TITLE
[dist] imagemin gibt Fehler bei Erstellen einer dist

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#242]
Musste das R+V-Logo händisch rüber kopieren.

Fehlgeschlagene Versuche:
- imagemin auszukommentiere
- alle Grafikenohne Transparenz
- alle einheitliche Grafikformate (svg, jpg, png)

**Comment by MarcelMP** [comment]
http://meshfields.de/continuous-integration-angular-fullstack/

Str+F "Imagemin" eingeben. An der angezeigten Stelle wird ein Lösungsvorschlag erläutert, vll kann man damit den Bug beheben.

**Comment by Nullmann** [comment]
Der Link hat nur etwas mit Mac zu tun..

**Comment by Nullmann** [comment]
Lässt sich händisch beheben, wenn man das R+V-Log bei jedem Erstellen einer neuen dist in den Ordner "images" der dist kopiert.

**Comment by Nullmann** [comment]
Grunt läuft ohne Probleme durch
