### ISSUE TITLE
Dateninkonsistenz - Stadt wird nicht gezeichnet

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#246]
Erst mach Filterung/Einstellungen, d.h. Eingrenzen der Daten, der Ansicht konnte konnte bspw der Datensatz SG57 gezeichnet werden.
Dieses sollte angefangen werden.

**Comment by Nullmann** [comment]
Gestern trat der Feher einer komplett grauen Ansicht bei dem SG57-Datensatz bei bestimmten Dimensionsn auf. Wenn ich mich richtig erinnere bei der Ansicht "Marcus SG57". Diese funktioniert bei mir nun. Könnte mit #201 behoben worden sein.
Habe ebenfalls versucht viele Permutationen der Dimensionseinstellungen auszuprobieren, welche alle ausnahmslos geklappt haben.
