### ISSUE TITLE
Scrollbalken und Scrollradfunktion nicht mehr gegeben

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#247]
Bei Aktualisierung der Stadt verschwinden mehrere Funktionen wir Scrollbalken, Scrollradfunktion,... Tab muss neu geladen werden.

**Comment by Nullmann** [comment]
Kann ich nicht mehr reproduzieren. Selbst nach mehrmaligem Aktualiseren der Stadt und mit IE.

**Comment by ManuelMueller1988** [comment]
Dann schließen wir das.

Sollte es nochmal auftreten, wird der Issue wieder aufgemacht.
