### ISSUE TITLE
[Verbindungen per Klick auf Gebäude] Mehrmals klicken für Verbindungen

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#248]
In der aktuellen Dist muss man mehrmals auf 'Verbindungen anzeigen' anklicken, bevor sich etwas tut.

**Comment by Nullmann** [comment]
Es muss genau zweimal auf die Checkbox geklickt werden, damit sich diese ändert.

**Comment by JuliaH1** [comment]
Ich weiß nicht woran es liegt, kann es auch irgendwie nicht beheben... Bei der Checkbox "Gebäude mit Verbindungen" geht es ja mit einem Klick, kann es mir deshalb auch nicht erklären

**Comment by Nullmann** [comment]
Scheint mit e46ae15008d6394638278e139ca2282ebe833c12 behoben zu sein. War vermutlich eine überflüssige if-abfrage

**Comment by Nullmann** [comment]
Ist mit den Veränderungen in Issue #260 nicht mehr nötig.
