### ISSUE TITLE
Haken entfernen für Verbindungen bei Selektion eines anderen Gebäudes

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#251]
Nachdem für ein Gebäude ein- oder ausgehende Verbindungen ausgewählt wurden sollte die Selektion für weitere Gebäude wieder entfernt werden, d.h. Der Haken rausgenommen im Menü

**Comment by Nullmann** [comment]
Wird bereits in Issue #243 behandelt.
