### ISSUE TITLE
Legende für Farbbedeutungen

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#252]
Nützlich, aber im momentanen Zeitdruck Prio zwei

**Comment by Nullmann** [comment]
Ein Beispiel dafür hier:
http://threejs.org/examples/webgl_geometry_colors_lookuptable.html

**Comment by Nullmann** [comment]
Eventuell in den Client?

**Comment by thuylinhluu** [comment]
Wollen wir denn so ein Bild und wenn ja, wo soll das denn hin?

Was ich anbieten könnte wäre evtl. ein paar mehr Zeilen im Dropdownmenü unter "Legende" zu packen, oder dass man wenn man da auf etwas klickt, dass ein Fenster aufpoppt und dort die Farben ausführlicher erklärt werden. Oder wir machen das nicht in dem Teil....

**Comment by ManuelMueller1988** [comment]
Wie in und nach der Telko angesprochen, würde ein separates Fenster, bspw. unten rechts, Sinn machen.

**Comment by ManuelMueller1988** [comment]
Finde ich gut. Statt "Verbindungen" könnte man vielleicht "Anzahl Verbindungen" schreiben? Weil ein neuer Nutzer weiß vielleicht nicht was der Farbverlauf zeigen soll.
Das Einklappen funktioniert im IE nicht, trotz des angezeigten Pfeils.

**Comment by JuliaH1** [comment]
Das Einklappen der Farblegende klappt auch bei Firefox nicht. Meiner Meinung nach muss es auch nicht einklappbar sein. Dann bitte den Reiter in eine Art Infobox umändern, damit es nicht aussieht, als könnte da man was öffnen oder schließen

**Comment by Nullmann** [comment]
Das Wording wurde mit Commit 51affa0582bdf062150078a6668ee48ed79587a6 auf "Anzahl Verbindungen" verändert.
Ich habe es nicht hinbekommen, dass man dort den Pfeil weg machen kann. Wenn man es nicht nochmal in einen Unterordner packt, kann man die Legende überhaupt nicht mehr zuklappen.
Ich schätze mal, dass es damit zu tun hat, dass die dat.gui.js eigentlich nicht dafür ausgelegt ist, dass man Bilder dort einfügen kann und Steffen da ziemlich herumfummeln musste, bis das überhaupt ging.

**Comment by JuliaH1** [comment]
Wenn das so ist, dann kann der Issue meiner Meinung nach geschlossen werden. Es erfüllt ja seinen Zweck, und ob da nun ein Reiter ist, den man nicht öffnen kann, ist auch nur Kosmetik

**Comment by Nullmann** [comment]
Dann schließe ich es.
