### ISSUE TITLE
[Optik] Zusätzliche Option, ob die Vorgärten gezeichnet werden sollen

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#255]
Zu dem Punkt 2 "Verbindungen" hinzufügen.

**Comment by Nullmann** [comment]
Ich habe diese Option hinzugefügt, da ich die Bedienung mit den Gebäuden, wie in Issue #243 beschrieben, nicht intuitiv finde. Man muss dort drei Klicks machen (Alle Gebäude highlighten, ein gebäude anklicken, sich dann per Checkbox die ein- oder ausgehenden Verbindungen anzeigen lassen), sodass für mich die (bugfreien) Vorgärten mit einem Klick schöner sind.

**Comment by MarcelMP** [comment]
Sollte das Feld für die Verbindungen wirklich mittig dargestellt werden? Finde alles linksbündig eigentlich schöner. An sich eine gute Idee es drin zu belassen. Dann hat man bei Verbindungen noch mehr Entscheidungsfreiheiten

**Comment by Nullmann** [comment]
Danke für den Hinweis, das ist mir bei meinem Bildschirm mit der Konsole auf der rechten Seite nicht aufgefallen :)

**Comment by JuliaH1** [comment]
Finde es eine gute Idee, die Wahl zu haben, die Gärten unter "Verbindungen" hinzu zu nehmen

**Comment by Nullmann** [comment]
Funktion funktioniert.
