### ISSUE TITLE
[Optik] Gebäude und Ebenen werden falsch gesetzt

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#256]
Collection: 100.000 Länderdaten

Ansicht: Gebäude ragen über dem Distrikt hinaus
![screenshot 2016-03-15 11 37 21](https://cloud.githubusercontent.com/assets/15816473/13775052/b98be9de-eaa2-11e5-858f-d50fa83b8da8.png)

Ansicht: Komplett falsches Setzen der Gebäude und Ebenen
![screenshot 2016-03-15 11 37 00](https://cloud.githubusercontent.com/assets/15816473/13775063/c59f13e0-eaa2-11e5-9b68-96acc959022a.png)

Um so weiter der Maximum-Filter für den BIP nach unten gesetzt wird, umso eher wird eine Schneise geschnitten und die Ebenen falsch gesetzt.

**Comment by Nullmann** [comment]
Auch, wenn es befremdlich aussieht, werden die Gebäude richtig dargestellt. Es läuft etwas beim Setzen der Gebäude und Ebenen schief. Wenn alles bündig gesetzt werden würde, ist die Darstellung hier in Ordnung.

**Comment by Nullmann** [comment]
Das Problem liegt irgendwo in Stadtteil.js in der Funktion "setOneDistrict"

**Comment by thuylinhluu** [comment]
Ich hab noch nicht gepullt nach meinem Urlaub. Mit meiner alten Version ist alles richtig gesetzt...

**Comment by Nullmann** [comment]
Sieht jetzt wieder gut aus, wird also geschlossen.
