### ISSUE TITLE
DropDownMenü: Die Checkboxes für die Verbindungen in einen eigenen Folder

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#261]
Ich finde, dass das in dem Ordner "Gebäudeinformationen" nichts mehr zu tun hat, weil es nun gebäudeübergreifend ist. Also entweder in einen neuen Folder oder ggf unter "Steuerung"?

**Comment by ManuelMueller1988** [comment]
Ja, das war intuitiv auch mein erster Gedanke, als ich es beim ersten mal benutzt hatte. Finde den Vorschlag gut.

**Comment by Nullmann** [comment]
Wurde umgesetzt und bisher von Niemamden als schlecht empfunden, wird daher geschlossen.
