### ISSUE TITLE
Stadt wird nicht gezeichnet, Ladebalken hängt bei 70%

### ISSUE THREAD

**Issue by ManuelMueller1988** [Data-City/client#262]
Wenn ich eine Stadt erstellen möchte mit Verbindungen, ohne Vorgärten, bleibt der Ladebalken bei 70% stehen. Danach tut sich nichts mehr.
Getestet bei RuVBeispieldaten und SG57 Datensätzen.

![0000000_2016_03_17_04_41_40_datacity_internet_explorer](https://cloud.githubusercontent.com/assets/15968962/13835739/3aef4df0-ebfb-11e5-8d02-58f46c5b2db6.png)

**Comment by Nullmann** [comment]
Bei mir klappt's in der Collection RuVBeispieldaten und Benedikts Ansicht.
Ist vermutlich eine inkonsistenz bei einer Ansicht, da ich so vie geändert habe. Neue Ansichten sollten funktionieren.

**Comment by Nullmann** [comment]
Der Fehler trat nur bei alten Ansichten auf, nicht bei neu erstellten. Für diese wurde ein Hotfix eingespielt. Bei weiteren Problemen wieder öffnen oder neuen Issue erstellen.
