### ISSUE TITLE
Skalieren, nachdem Verbindungsgebäude gehighlighted wurden

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#263]
Nachdem man in der checkbox die Gebäude mit Verbindungen highlighted und dann skaliert, ist in der Checkbox der Haken noch gesetzt, aber die Gebäude sind nicht mehr gehighlighted

**Comment by thuylinhluu** [comment]
Jetzt werden sie immer gehighlighted, wenn man skaliert =D

**Comment by Nullmann** [comment]
Wieder öffnen, falls hier noch Bugs auftreten.
