### ISSUE TITLE
[Optik] Platz für Gärten sind da, obwohl keine gezeichnet werden

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#264]

**Comment by Nullmann** [comment]
Collection: 100.000 Länderdaten; Ansicht: "Gebäude ragen über den Distrikt raus"

Bei dem SG57-Datensatz sieht das Ganze gut aus. Werden Vorgärten gezeichnet ist genug Platz, ohne die Vorgärten entsprechend wenig. Hier der Vergleich:
![mit vorgarten](https://cloud.githubusercontent.com/assets/15816473/13843250/cc21f462-ec32-11e5-8faa-4629bef3cba4.png)
![ohne vorgarten](https://cloud.githubusercontent.com/assets/15816473/13843253/ce28001c-ec32-11e5-92e2-dbb5a534cee1.png)
