### ISSUE TITLE
Für den Link für eine gespeicherte Ansicht: Verbindungen aktualisieren

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#269]
Man müsste noch darin speichern, ob Verbindungen ausgewählt wurden und ob eingehende und ausgehende Verbindungen ausgewählt wurden und da einen entsprechenden Haken machen.

**Comment by Nullmann** [comment]
Und das dann auch dementsprechend in der "setSpecifcView"-Funktion ändern, sodass das auch Auswirkungen hat

**Comment by Nullmann** [comment]
Alle Checkboxes werden in die gespeicherte Ansicht übertragen.
Auch die Gebäude bleiben gehighlighted.

Falls Probleme auftreten, wieder öffnen
