### ISSUE TITLE
[Optik] Gebäude ragen über die Ebenen hinaus?

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#270]
![bundige gebaude](https://cloud.githubusercontent.com/assets/15816473/13856176/40e4709a-ec74-11e5-94a0-f5e9c67d4ed0.png)

Collection: SG57; Ansicht: Benedikts Versuche

**Comment by aloske** [comment]
![2016-03-17](https://cloud.githubusercontent.com/assets/17452353/13856295/d847a704-ec74-11e5-88ad-f3d6a9b01427.png)

**Comment by Nullmann** [comment]
@aloske Ich schließe den Issue mal, da er anscheinend bei dir ein "Firefox only" Bug ist, wir primär für den Internet Explorer programmieren und er bei uns bisher nicht mehr aufgetreten ist (..und damit die Issue-Landschaft aufgeräumt wird). Bitte wieder öffnen, falls das so nicht in Ordnung ist.
