### ISSUE TITLE
Farbverlauf bei Gebäuden mit Verbindungen highlighten

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#271]
hellgelb -> dunkelgelb?

**Comment by thuylinhluu** [comment]
Wie wird sie gewichtet? Durchschnitt aus ausgehende und eingehende Verbindungen?

**Comment by Nullmann** [comment]
Entweder das oder die Summe.
Ich denke, dass der genaue Farbverlauf egal ist, weil man sowieso den Unterschied zwischen zwei Gelbtönen nicht mit dem Auge erkennen kann. Man sollte halt nur einen Unterschied erkennen können. Wie bei den Farbverläufe bei den Vorgärten.

**Comment by thuylinhluu** [comment]
so ok?

**Comment by Nullmann** [comment]
Welche Farbverläufe findet ihr besser? Ich fande den eben etwas schwach.
![gelbtone](https://cloud.githubusercontent.com/assets/15816473/13859100/01c142fe-ec82-11e5-8d4e-545945fe391f.png)
```
var colorOfBuildingsWithConns = 0xFFBF00;
var colorYellowBright = 0xF4FA58;
```
![orangetone](https://cloud.githubusercontent.com/assets/15816473/13859162/55ff55d6-ec82-11e5-9492-ecd6b017b39c.png)

```
var colorYellowBright = 0xFFA500;
var colorYellowDark = 0xFF0000;
```


Ihr könnt ja selbst mal mit den Farben etwas rumspielen :)

**Comment by thuylinhluu** [comment]
nimm das untere^^

**Comment by Nullmann** [comment]
Funktioniert, Farbverläufe sind nun besser erkennbar.
