### ISSUE TITLE
Den Abstand zwischen den gebäuden etwas größer gestalten

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#275]
Damit man zwei Gebäude besser voneinander differenzieren kann

**Comment by Nullmann** [comment]
Sieht das so besser aus, @aloske?

![von der seite](https://cloud.githubusercontent.com/assets/15816473/13858570/883b6556-ec7f-11e5-9a26-5333f64a9ca9.png)
![von oben](https://cloud.githubusercontent.com/assets/15816473/13858574/8a1352e4-ec7f-11e5-80d4-d5e1dd69159a.png)

**Comment by aloske** [comment]
Vielen Dank für die Anpassung @Nullmann. Die Abstand bei den kleinen Gebäuden sieht aus meiner Sicht gut aus. Die großen Gebäude oben links kleben aber immernoch aneinander.

**Comment by Nullmann** [comment]
@aloske Würde das so besser aussehen? (ist noch nicht in der dist)

![gap x 20](https://cloud.githubusercontent.com/assets/15816473/13873864/8e992b2a-ecf4-11e5-80b2-764311397863.png)

Da der Abstand (gap) zwischen allen Gebäuden gleich ist, sitzen nun die kleinsten Gebäude für meinen Geschmeack etwas weit auseinander, aber insgesamt kann ich beiden Versionen etwas abgewinnen.

**Comment by aloske** [comment]
Finde ich besser.
