### ISSUE TITLE
WebGL-Ansicht per Link: Straßen statt Bögen

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#277]
Ich war bei dem RuV-Datensatz mit der neuen Ansicht (ganz oben) und habe Verbindungen ausgewählt mit Bögen. Beim Aufrufen mit dem Link wurden aber irgendwie Straßen gezeichnet.

**Comment by Nullmann** [comment]
Das Problem bestand darin, dass vorher schon einmal der experimentelle Modus aktiviert und die Straßen ausgewählt worden waren. Nun werden standardmäßig die Bögen gespeichert, wenn man den Modus wechselt.
Dies klappt natürlich nur dann, wenn für bestehende Ansichten der Modus geändert wird. Deshalb ein Hotfix, damit nicht alle alten Ansichten geändert werden müssen.
