### ISSUE TITLE
Spaltenname "buildings" könnte zu Komplikationen führen

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#278]
Wenn man bei der CSV-Datei einen Spaltennamen "buildings" hat und diesen als Dimension auswählt, könnte es zu Problemen kommen, weil man mit Gebäude.buildings eigentlich auf etwas anderen auch zugreifen wollte.

Möchten wir unser Attribut überall zu _buildings umbennen oder dem Kunden sagen, er soll sich doch bitte wenn dann den Namen "Buildings" verwenden oder einen komplett anderen Namen nehmen...?

**Comment by SteffenPegenau** [comment]
Vielleicht könnten wir an der Stelle darauf hinweisen, an der wir auch sagen, dass es zu Problemen kommt, wenn die ID nicht eindeutig ist.

Könnten ein Zeichnen der Stadt auch mit Fehlermeldung abbrechen wenn eine Dimension buildings heißt. Umbenennen zu _buildings sehe ich skeptisch, weil relativ viel angefasst werden müsste.

**Comment by Nullmann** [comment]
Ich habs jetzt so umgesetzt, dass es eine Warnung gibt, wenn eine ausgewählte Dimension "buildings" heißt. Trotzdem wird versucht die Stadt zu bauen, es wird also nicht abgebrochen.
Damit schließe ich den Issue aufgrund von einem sehr geringem Use Case. Der Nutzer wird in dem Fall ja informiert, wieso es zu Problemen kommt.

**Comment by thuylinhluu** [comment]
öööh ich habs nicht ausprobiert, aber ist das nun in Schritt 4? Gehört das nicht eher in Schritt 5, wenn der Nutzer als eine Dimension "buildings" aussucht?

**Comment by Nullmann** [comment]
Es ist in gar keinem Schritt direkt eingebaut. Es wird lediglich eine Warnmeldung _beim Erstellen der Stadt_ ausgegeben, wenn in Schritt 5 eine Dimension mit dem Namen "buildings" ausgewählt wurde.

**Comment by thuylinhluu** [comment]
eigentlich klappt so ziemlich nichts, wenn irgendwo in der spalte ein buildings drinsteckt^^

**Comment by thuylinhluu** [comment]
Ich hab keine Fehlermeldung bekommen, als ich buildings als Dimension eingestellt hab.

**Comment by Nullmann** [comment]
Hatte die Felder falsch abgefragt, so stimmt es nun. 
Mit dem Test wissen wir nun aber, dass dann die Gebäude gezeichnet werden, aber keine Ebenen. Somit klappt schon etwas.
Schließe ihn wieder.
