### ISSUE TITLE
2. Schritt: Verbindungen auswählen: Beschreibungsfehler

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#279]
a) Wenn man mit der Maus auf das Fragezeichen nach "Verbindungen nutzen" geht, ist die Beschreibung nicht mehr richtig, denn es werden mit dem Haken keine Vorgärten gezeichnet.

b) Die Erklärung der Farben kommt nur im experimentalen Modus. Ich glaube nicht, dass das so sein soll.

**Comment by Nullmann** [comment]
a) Habe es angepasst, bin mir aber nicht ganz sicher, ob das Wording jetzt so stimmt. 

b) wurde geändert
