### ISSUE TITLE
Dinger bei den 5 Schritten lassen sich nicht zuklappen

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#280]
Wenn man ein Dingensda runterklappt und dann wieder zuklappen möchte, geht das nicht.

Wenn das so sein soll, dann kann der Issue wieder geschlossen werden.

Ich hoffe man versteht was gemeint war^^

**Comment by Nullmann** [comment]
Die "Dinger" sind Panels :D
Es war eine Anforderung, dass sich alle anderen Panels schließen, wenn man auf ein Neues klickt. Das hatte die Auswirkung, dass man sie nicht mehr schließen kann.
Da es bisher auch nicht anders gewünscht ist, würde ich den Issue schließen?

**Comment by thuylinhluu** [comment]
Wenn das ein Haufen mehr Arbeit wäre, das zu ändern, dann schließ es^^
