### ISSUE TITLE
1. Panel ( = Dinger) bei Schritt eins: das Fragezeichen sagt nicht viel aus

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#282]
Ist zumindest meine Meinung.

Die Aussage "Einzelne Schritte als SQL-Befehle verdeutlicht" bezieht sich dabei wahrscheinlich nicht nur auf Schritt 1, sondern auch auf die anderen. Aber so wie es da steht, sieht es so aus, als würde es nur sich auf Schritt 1 beziehen. Und in diesem Fall wüsste ich nicht, was einzelne Schritte sein sollen.

Dass das Select from where SQL-Befehle sind, sieht man aber ja eigentlich...

Ich würde vermutlich das Fragezeichen weglassen...

**Comment by Nullmann** [comment]
Habe es gerade so geändert, dass ich vor jeden Befehl "SQL" geschrieben und den Tooltip weg gemacht habe. Was haltet ihr davon?

![sql schritte](https://cloud.githubusercontent.com/assets/15816473/13899592/62aaa12a-edf2-11e5-95c0-7f5dcda83566.png)
