### ISSUE TITLE
etwas größere Testdatei: keine Ansichten zu sehen

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#283]
ist der link irgendwie falsch...?

**Comment by Nullmann** [comment]
Dort fehlt die Collection mit den Metadaten ("_dc_maxminav"). Alle neu importierten Collections besitzen diese (weiß auch nicht genau, wieso diese hier nicht).
Da der Datensatz allerdings genau der gleiche ist wie "100.000 Länderdaten", nur auf 10.000 begrenzt, lösche ich ihn und schließe den Issue.
