### ISSUE TITLE
Nach Aktualisierung der Stadt gibt es Fehler

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#285]
Unter anderem: wenn man auf den einen Garten klickt, geht ein anderer Garten an... 

bzw. die Gärten wurden nicht dem richtigen Gebäude zugeordnet.

Und irgendwie sind auch noch Gebäude unsichtbar auf der Canvas, die da gar nicht mehr da sein sollten nach der Filterung. Wurde vielleicht die alte Canvas nicht entfernt? Könnte man vielleicht, wenn die Stadt aktualisiert wurde, der WebGL-Canvas eine neue div-ID geben? Vielleicht kommt es da irgendwie zu Komplikationen.

**Comment by Nullmann** [comment]
Eigentlich wird bei jedem Klick auf den Button die Funktion aufgerufen:
![removewebgl](https://cloud.githubusercontent.com/assets/15816473/13899845/f543f0cc-edf7-11e5-89f7-7d22f9c7ad2a.png)

Was man machen könnte, wäre das div-Element nicht in der Seite hart zu verankern, sondern diese im WebGL-Teil jedes mal dynamisch zu erstellen? Wie es auch die three.js-Beispiele machen: 

```javascript
container = document.createElement('div');
document.body.appendChild(container);
```

----------------------
Selbst konnte ich den Fehler allerdings noch nicht nachstellen. Was hast du denn genau gemacht?

**Comment by thuylinhluu** [comment]
Gehe auf RuVDatensatz, gehe zur Ansicht "Issue 285". Bei Schritt 1 ist bei Klassen ein Haken. Falls da das Maximum nicht auf 69 ist, so stelle das Maximum auf 69. Klicke auf Stadt aktualisieren.

Schaue in der Stadtansicht, wo das Gebäude "de.ruv.vrrente.ui.beans" ist (es ist das größte hinten links).

Nun gehe nach oben wieder zu Schritt 1 und stelle das Maximum von "Klasse" auf 17 oder so.
Klicke auf Stadt aktualisieren.

An der Stelle, wo eben "de.ruv.vrrente.ui.beans" stand, steht es immer noch unsichtbar. Die Gärten und Gebäude, die an der Stelle stehen stehen, wo das fette Gebäude steht, kann man nicht mehr anklicken.

**Comment by thuylinhluu** [comment]
Ich bekomme die letzte Stadtansicht einfach nicht weg, ich weiß nicht was ich da machen kann.
Ich habe jetzt versucht, es zu umgehen. Ich hoffe, es funktioniert so und ich hoffe, ich habe keine Fehler eingebaut.

@Nullmann  ACHTUNG: Dafür habe ich die ID von der WebGLCanvas umgeändert zu "WebGLCanvas"+EineNummer. Sollte irgendwas außerhalb vom WebGL davon betroffen sein - was ich nicht hoffe - sagt bitte Bescheid...

Ich schließe das mal ...

**Comment by Nullmann** [comment]
Ich öffne es mal wieder, weil es im Client noch ein paar Sachen gibt, die daran angepasst werden müssen. Mache ich heute Abend.

**Comment by Nullmann** [comment]
Hab's mir nochmal angeschaut. Alle Funktionen im WebGl rufen "removeWebGLCanvasFromDomElement" auf, welche von dir bereits entsprechend umgeschrieben wurde. Somit schließe ich den Issue.
