### ISSUE TITLE
Fehler abfangen, wenn durch Datenreduzierung keine Gebäude übrig bleiben?

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#286]
Stellt man beim RuV-Datensatz ein, dass man nur Gebäude mit Klassenanzahl 69 (haha) und 2 Methoden haben möchte, gibt es keine Gebäude zu zeichnen. Die Fehlermeldung taucht aber schon vorher auf. Wollen wir hier eine Fehlermeldung für den Nutzer einbringen?

**Comment by Nullmann** [comment]
Sollte behoben sein. Der Ladebalken verschwindet dann auch wieder.
@thuylinhluu ist das so, wie du es wolltest?
