### ISSUE TITLE
Wechsel in den Experimental-Modus

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#287]
Wenn man Verbindungen bereits ausgewählt hat und dann in den experimentalen Modus wechselt, kommt die Fehlermeldung "Es wurden Verbindungen, aber keine Option ausgewählt", obwohl Bögen automatisch bereits ausgewählt wurden. Man muss selbst nochmal auf "Bögen" klicken, damit es geht

**Comment by Nullmann** [comment]
Javascript hat aus einer Null ein false gemacht, sodass die Abfrage falsch war.. Ist nun behoben.
