### ISSUE TITLE
Marcels Issue

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#288]
kopiert von Facebook:
"habe irgendwie das Problem, wenn ich die experimentelle version aktiviere und mir dann irgendeinen datensatz anzeigen möchte, ist das dropdownmenü fehlerhaft und wird nicht komplett geladen. die stadt auch nicht:"
![12721792_688014461338251_2116906843_n](https://cloud.githubusercontent.com/assets/15816473/13899648/dc242d9a-edf3-11e5-9287-f77d100f35b2.jpg)

**Comment by Nullmann** [comment]
@MarcelMP Welche Collection? Welche Ansicht? Was sagt die Konsolenausgabe?
Ich persönlich konnte den Fehler nicht reproduzieren.

**Comment by thuylinhluu** [comment]
Wir auch nicht, es trat ein Fehler mit logarithmicWidth auf, was bei mir damals auch aufgetreten ist und ich dir dann schrieb, ich hätte es auskommentiert etc. etc.
Es war eine alte Ansicht gewesen. Vielleicht lag es daran?

**Comment by MarcelMP** [comment]
Es war vermutlich eine veraltete Ansicht gewesen. Habe eine neue Ansicht erstellt und der Fehler trat nicht mehr auf. Kann damit geschlossen werden.
