### ISSUE TITLE
Steffens ToDo's

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#289]
1) Lut-Sachen löschen
2) Was macht in ClientWebGL.js die Methode doDispose? --> Kommentieren oder löschen

**Comment by Nullmann** [comment]
Zu 2) Die Funktion wurde eingebaut, als versucht wurde den Speicherverbraucht zu verbessern. Da diese Änderungen wieder rückgängig gemacht wurden, wird die Funktion überhaupt nicht mehr aufgerufen und ist somit eigentlich obsolet.
