### ISSUE TITLE
Im Datensatz LinhTest -> Ansicht Linhs Ansicht ist kein Beispiel des Datensatzes

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#290]
Ich sehe nur die Spalten, aber keine Einträge :/

'Aber davor kommt auch so eine Fehlermeldung in der Konsole...

**Comment by Nullmann** [comment]
Das Problem lag darin, dass ng-repeat von angular. js keine Duplikate beinhalten darf.
Das Array in dem Datensatz war [20, 0.78, 19, 20, 456, "uio", 2].
Es konnte durch ein Einfaches "track by $index" behoben werden. Für mehr Infos, siehe:
https://docs.angularjs.org/api/ng/directive/ngRepeat
