### ISSUE TITLE
1 Fall: man muss in den Block reinzoomen, um die Stadt zu sehen

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#291]
Siehe LinhTest --> Ansicht Issue 291

Da sieht man 2 Blöcke ohne Stadt. Wenn man aber in die beiden Blöcke reinzoomt, sieht man, dass die Stadt sich in den Städten versteckt hat. Die Höhe der Böden ist irgendwie komisch...?

**Comment by Nullmann** [comment]
Nicht die Höhe der Böden ist komisch, sondern die Dicke der Böden. An der habe ich eigentlich nie etwas geändert. Hier ein Screenshot:
![dicke der ebenen](https://cloud.githubusercontent.com/assets/15816473/13907075/3d9661ea-eee6-11e5-884c-3b149a80fed0.png)

In der gui.js Zeile 306 wird die Geometrie der Ebenen gesetzt:
```javascript
var boxGeom = new THREE.BoxGeometry(1, 1, 1);
```
Ich bin mir nicht sicher, wie du diese später anpasst, würde aber schätzen, dass sie nur hochskaliert werden, aber nie runter. D.h. (1,1,1) ist das Minimum der Ebenen.
In diesem Fall scheinen die Gebäude ziemlich klein zu sein, sodass die Ebenen im Vergleich riesig sind und diese sogar "einbetten".

Oder wie siehst du das?

**Comment by thuylinhluu** [comment]
ich hab was committed. Meinst du das wäre so ok?

**Comment by Nullmann** [comment]
ja, das ist so in Ordnung. Ich schließe den Issue somit.
