### ISSUE TITLE
Wechseln von Ansichten: Änderung speichern bleibt bestehen

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#292]
Wenn ich auf eine Ansicht öffne, da irgendwas ändere, erscheint der Button "Änderungen speichern".
Dann wechsel ich, ohne zu speichern, auf eine andere Ansicht. Der Button "Änderungen speichern" bleibt da, obwohl ich nichts an der 2. Ansicht geändert habe.

**Comment by Nullmann** [comment]
Das hatte zwar eigentlich keine negativen Implikationen, weil man dadurch nichts "kaputt" machen kann, habe es dennoch geändert und schließe den Issue.
