### ISSUE TITLE
Alle Dimensionen werden mit der Breite skaliert

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#294]
Soll das so sein?

Ich habe in LinhTest -> Issue 294 als Höhe "irgendwas", das ist immer entweder 1 oder 2. Bei der skalierung wird dann durch ca. 99 geteilt, und dann werden alle Gebäude so flach. Wollen wir nicht lieber die Höhe durch die Höhe und die Breite durch die Breite teilen und die Farbe brauchen wir ja eigentlich auch überhaupt nicht teilen...

**Comment by Nullmann** [comment]
Ja, das soll so sein. Dadurch wird gewährleistet, dass die Relationen der Höhe zu der Fläche gleich stimmen. Hat man zum Beispiel die Höhe 1 und die Fläche 50, so ist die Breite 50 mal länger als die Höhe.
Mit deiner vorherigen Skalierung wurde das kleinste Gebäude auf die Größe (1,1,1) normiert, selbst wenn die Dimensionen 1 und 50 hießen.
Wenn man das nicht haben möchte, kann man die Höhe bzw die Fläche ja logarithmieren.

**Comment by thuylinhluu** [comment]
Ich finde man braucht hier die Relationen von Höhe und Fläche nicht gleich halten. Beispielsweise nimmt man als Spalte einmal kg und einmal km, dann wäre das auch nicht sinnvoll in Relation zu halten. (Wenn ich es jetzt nicht falshc verstanden hab)

**Comment by Nullmann** [comment]
Wenn ich aber eine Zahl als Breite nehme, die um ein Vielfaches größer ist als die Zahl der Höhe würde ich als Benutzer davon ausgehen, dass die Fläche dann auch dementsprechend größer sein wird. So gehen auch überhaupt keine Informationen durch die Skalierung verloren.

**Comment by Nullmann** [comment]
Aufgrund des eventuell entsehenden Informationsverlustes und nach privater Diskussion schließe ich das hier.
