### ISSUE TITLE
Filter-Regler zeigen nicht richtigen Werte an

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#295]
Wenn man die Daten reduziert soll sich der Avg-Wert ja ändern bei der Anzeige. Oder soll der sich nicht ändern? Wenn der sich nicht ändern soll, dann wurde alles richtig gemacht.
Wenn er aber geändert werden soll, dann stimmt das irgendwie nicht so ganz, denn ich habe unter
linhtest -> issue 295 unter dem Attribut "irgendwas" nur 1 und 2, und das gleich viel. Jetzt schiebe ich den Regler so, dass ich nur noch 1 drin habe --> Der durchschnitt ist immernoch 1.5

**Comment by Nullmann** [comment]
Nein, der soll sich nicht ändern. Er soll statisch sein, wird beim Import berechnet und soll nur eine zusätzliche Information über die Dimension darstellen.
Wird dadurch geschlossen.
