### ISSUE TITLE
1. Schritt: Daten reduzieren: Pfeile bei den "Eingabefeldern"

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#296]
Die Pfeile gehen irgendwie nicht... bei mir zumindest. Wollen wir sie einfach wegmachen, wenn das geht?

Und es sieht aus wie ein Eingabefeld, aber ich kann da nichts eintippen.

Ich hab ewig gebraucht, um zu sehen, dass man diese Eingabefelder mit dem Mausrad ändern kann und sonst mit nichts, denn die Schieberegler springen irgendwie auch nur von 0 auf 1 oder andersrum. 
Evtl. wäre hier so ein Fragezeichen angebracht.

[Edit] Mein Fehler: Man kann mit den Schiebereglern hervorragend das ändern^^ nur bei Kommazahlen gehts nicht, aber da gehts auch mit dem Mausrad nicht. Evtl. ändern...

**Comment by Nullmann** [comment]
Die "Pfeile" funktionieren, sind aber browserspezifisch. Beim IE sind die z.B. überhaupt nicht da.
Man kann auch in die Eingabefelder die Zahlen eingeben, die man als Filter haben möchte.

Das Problem hier liegt allerdings bei den Kommazahlen, die von dem Slider nicht unterstützt werden..
