### ISSUE TITLE
Stadt wird nicht angezeigt

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#298]
Big Data --> Issue 289

**Comment by Nullmann** [comment]
Der Bug ist schon ziemlich lange bekannt, siehe Issue #144 
Das Problem liegt nicht am Programm, sondern an dem Datensatz, der buggy ist, wodurch man die ID nicht als die Dimensions "ID" speichern kann.

Allerdings wurde dadurch ein anderer Fehler aufgezeigt: Es wurde mit Issue #278 bei der Inputvalidierung eine Funktion aufgerufen, die auf Felder der Dimensionen zugriff, bevor geprüft wurde, ob diese überhaupt gesetzt sind. Das ist jetzt behoben.

Schließe den Issue.
