### ISSUE TITLE
cdnify funktioniert nicht

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#3]
Wenn ich die Distribution erstelle (grunt ausführe), kommt er nicht über den Task cdnify hinaus. Nach 30 Minuten habe ich abgebrochen und den Task in der gruntfile raus geschmissen.
Müsste doch an der Internetverbindung oder Google liegen, oder? Könnte daran liegen, dass das Uninetz in letzter Zeit ziemlich lahm ist...
So schlimm ist das nicht, weil die Skripte (Angular, Bootstrap) eigentlich auf dem Neuesten Stand sein müssten und so schnell auch keine neuen, wichtigen Updates draußen sein werden, denke ich.

**Comment by SteffenPegenau** [comment]
Bitte erneut testen

**Comment by Nullmann** [comment]
Jap, daran lags. Dummes Uni-Internet.
