### ISSUE TITLE
sollte nicht nach einer skalierung gap auch aktualisiert werden?

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#301]

**Comment by Nullmann** [comment]
Was meinst du damit genau? Meinst du deinen Commit 21844d8422cd92bccd69bf945004bab02c8db78b ?

**Comment by thuylinhluu** [comment]
wie macht man das mit den commits da anzeigen in einem Beitrag?

ich meinte eher diesem Commit hier:
https://github.com/Data-City/client/commit/5c938760bae717153f12c40b33e96ac752143ad0

ich hoffe, das ist ok?
