### ISSUE TITLE
Gebäudesuche nach einem leeren String findet Boden

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#302]
Wenn man den Input der Suche leer macht und Enter drückt, wird der Boden gefunden und gehighlightet. Ich finde, bei "" (also nichts) sollte auch nichts gefunden werden. Wenn man aus Versehen auf Enter drückt, nachdem man "Bitte Gebäudenamen eingeben" gelöscht hat, sollte das nicht passieren meiner Meinung nach, das verwirrt nur. 

![gebaudesuche](https://cloud.githubusercontent.com/assets/15839253/13952466/cb7f5b32-f036-11e5-8eeb-bf7e816b7375.png)

**Comment by thuylinhluu** [comment]
Ich hab dem Boden die ID "" gegeben, damit man die Namen der anderen Gebäude setzen kann. Wenn er nichts eingibt und bei der Gebäudesuche Enter drückt, bekommt der Nutzer die ganze Stadt zu sehen.

**Comment by thuylinhluu** [comment]
geändert. Jetzt wird die unterste Ebene gar nicht mehr gefunden.
