### ISSUE TITLE
logScaling nicht immer in association für storedView

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#303]
Mir ist es aufgefallen bei
SG57MitVerbindungen

die storedView geht nicht, weil assocition.logScaling undefined ist.
Liegt es vielleicht daran, dass der Datensatz schon älter ist oder so...?

**Comment by Nullmann** [comment]
Nein, an dem Datensatz sollte das nicht liegen. Das liegt dann aber vermutlich an alten Ansichten.

**Comment by thuylinhluu** [comment]
mit der Ansicht von heute gehts aber auch nicht

**Comment by Nullmann** [comment]
Wurde mit Issue #303 behoben.
