### ISSUE TITLE
Spaltenname lässt sich in Anzeige ändern

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#31]
- Immer Zeile 1 (so wie jetzt)
- Manuell eingebbar

**Comment by Nullmann** [comment]
Momentan übergeben wir nur die Daten von der MongoDB. Hier müssten wir diese Daten manipulieren.

**Comment by thuylinhluu** [comment]
Reicht es, wenn der Nutzer im Dropdownmenü beim WebGL das ändern kann wie er lustig ist oder ist das eher nicht gewünscht?

**Comment by JuliaH1** [comment]
Funktioniert nicht mehr

**Comment by thuylinhluu** [comment]
es funktioniert schon, wenn man das Feld markiert und dann den Spaltennamen mit Copy&Paste einfügt. Nur Eintippen klappt nicht... und den Buchstaben "P" eingeben geht auch nicht, weil man damit einen Screenshot macht - haha

**Comment by thuylinhluu** [comment]
Und ich weiß jetzt auch, woran es liegt: Wenn man nämlich die window.addEventListener im ClientWebGL.js entfernt, klappt es nämlich wieder, weil die Keys blockiert sind vorher
