### ISSUE TITLE
WebGL Repo in dieses Repo integrieren

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#32]

**Comment by Nullmann** [comment]
Mögliche Gründe, damit das nicht klappt:

![github](https://cloud.githubusercontent.com/assets/15816473/11867107/5946ac5a-a4af-11e5-8f8b-254c2d937ac7.png)

![diff](https://cloud.githubusercontent.com/assets/15816473/11867127/6d489ccc-a4af-11e5-8d1c-0f59e883a7c6.png)

**Comment by SteffenPegenau** [comment]
Erledigt mit 6ab80c749f7138cb17369db5d06ac751c6c30b6a
