### ISSUE TITLE
Range-Auswahl mit zwei Slidern

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#33]
Es sieht so aus, als ob man sowas nur mit JQuery hin bekommt

**Comment by Nullmann** [comment]
Scheint vielversprechend zu sein:
http://jqueryui.com/slider/#range

**Comment by SteffenPegenau** [comment]
Es scheint recht viele Angular-Module für Slider zu geben

**Comment by SteffenPegenau** [comment]
Slider eingebaut mit 15677a946edb8df5b7a63250a4b4adb6378ab0d8
