### ISSUE TITLE
Neue Ansicht erstellen: direkt anzeigen

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#4]
Wenn man auf den Button "Neue Ansicht erstellen" klickt, soll sich diese neue Ansicht direkt zur Bearbeitung öffnen.

Das ist aktuell scheinbar nicht der Fall, wenn vorher bereits eine Ansicht geöffnet war.

**Comment by Nullmann** [comment]
Selbst, wenn vorher kein Datensatz selektiert wurde, wird der Dialog nicht geöffnet
