### ISSUE TITLE
Mouseover / Mouseclick anpassen

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#40]
Zurzeit muss man runterscrollen, um das WebGL-Bild zu sehen.
Ich habe die Mausposition der Browserfenstergröße entsprechend berechnet, unter der Annahme, dass das WebGL-Bild das ganze Fenster füllt.
Das heißt, falls ein Abstand vom oberen bzw. linken WebGL-Rand zum oberen bzwl linken Rand des Fensters existiert, dann berechne ich die Mausposition für Mouseover und Mouseclick falsch. Hierfür gibt es folgende Möglichkeiten, die ich sehe:

1. Man übergibt mir den Abstand zum oberen Rand. Dies führt dazu, dass für die "Spielfläche" und für das Bild unter den Datensätzen 2 verschiedene Bilder erstellt werden müssten, oder zumindest eine andere Maus-Methode.
2. Man lässt das Bild unter den Datensätzen weg, um das Problem, dass der Abstand zwischen den 2 Rändern von dem Scrollen des Nutzers abhängt, zu umgehen. Dann zeichnen wir eben nur ein Bild unter der "Spielfläche"/"Stadtansicht", wobei die Höhe vom WebGL-Bild so verkleinert wird, dass der Nutzer nicht mehr scrollen kann.
3. Man überschreibt doch alles wieder, sodass das WebGL-Bild oben drauf auf alles kommt. Gerne kann ich einen "zurück-Button" einfügen.
4. Man erstellt doch woanders das Bild auf einer anderen html-Seite und bettet diese in die Seite ein.

Sollte ich jemand mit diesem Issue beschäftigen wollen und eine Lösung für das Problem gefunden hat, so bitte ich ihn, mir dies mitzuteilen, damit ich die Maus-Methoden anpassen kann.

**Comment by Nullmann** [comment]
Würde es funktionieren, wenn du die Berechnungen anhand der Position von dem div-Elemt machst?

Eine Abfrage müsste dann so aussehen:
var result = $("WebGLCanvas").height();

Beschrieben hier:
http://stackoverflow.com/questions/3839227/how-to-get-height-of-div-in-px-dimension

**Comment by thuylinhluu** [comment]
Das gibt mir glaube ich die Höhe vom Div-Element und nicht, wie weit der User runtergescrollt ist, aber ich glaube, zu schauen, wie weit der User runtergescrollt hat, kann man sich auch irgendwie anzeigen lassen. Ich probiers mal aus...

**Comment by Nullmann** [comment]
Ja, genau. Ich dachte, dass du genau das brauchtest.
Für die Scrollhöhe müsste hier etwas für dich dabei sein (je nachdem, ob du Javascript oder JQuery benutzen möchtest):
https://www.google.de/search?q=web+user+scrolled&ie=utf-8&oe=utf-8&gws_rd=cr&ei=C-J5VtmrDMz6aKaltbAH#q=javascript+distance+scrolled
