### ISSUE TITLE
Der Key "Verzweigungen" hat keinen Value und ist somit vom Typ String

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#41]
![key value](https://cloud.githubusercontent.com/assets/15816473/11929357/7210ee48-a7da-11e5-82e6-509a47c9164d.png)

**Comment by SteffenPegenau** [comment]
Das liegt daran, dass der erste Wert zur Ermittlung herangezogen wird. Der hat aber keinen Wert bei "Verzweigungen", weshalb String angenommen wird. Man könnte das Standardverhalten bei leeren Werten auf "number" ändern.

**Comment by Nullmann** [comment]
Hatte ich auch angenommen und versucht, anstatt den "nullten Wert" zu nehmen, andere Werte zu nehmen. Haben aber alle keinen Value.
Zudem ist der erste Wert in der csv-Datei drin:
![verzweigungen](https://cloud.githubusercontent.com/assets/15816473/11930483/0fcd90ec-a7e4-11e5-828a-cca8360fbc3d.png)

**Comment by SteffenPegenau** [comment]
Der erste Wert der CSV-Datei ist vermutlich nicht der erste im JSON... ;)

Könnte man solange weiter gehen, bis man eine Zeile findet, die den gesuchten Wert hat?

**Comment by Nullmann** [comment]
Die Logik funktioniert, allerdings wird bei dem Vergleich nicht darauf gewartet, bis ein Rückgabewert erzeugt wird. Gibt es eine Funktion, um auf die Daten zu warten?
