### ISSUE TITLE
Die Buttons "Änderungen speichern" bzw Verwerfen sollten nur auswählbar sein, wenn auch Änderungen gemacht wurden

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#43]

**Comment by SteffenPegenau** [comment]
Lässt sich ggf. über Angular Forms recht einfach umsetzen. Da wird ein Formular als "dirty" markiert, wenn der User etwas angepasst hat.

https://docs.angularjs.org/api/ng/type/form.FormController
