### ISSUE TITLE
Datei-Upload einer csv-Datei mit Import in der Mongo DB

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#44]

**Comment by Nullmann** [comment]
Man sollte die Collection dann auch umbenennen können

**Comment by JuliaH1** [comment]
Eine Sache, die mir aufgefallen ist: Der Button "Datei hochladen", der unter "Durchsuchen" steht, könnte man vorerst da weg nehmen, solange noch keine Datei zum Hochladen ausgewählt wurde. Und erst dann soll er erscheinen, wenn eine Datei gewählt wurde
