### ISSUE TITLE
Vorschau eines Datensatzes

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#45]
Sinnvoll wäre es, diesen in einem komplett neuem Fenster anzeigen zu lassen?

**Comment by SteffenPegenau** [comment]
Komplett halte ich nicht für sinnvoll. Ich habe auf der Arbeit mal so eine dynamische Tabellenanzeige mit ca 35.000 Datensätzen und ca. 6 Attributen gebastelt. Schon das war eine sehr lahme Geschichte. Denkbar ist die Darstellung der ersten 100 Datensätze oder so, um sich einen Eindruck zu verschaffen

**Comment by SteffenPegenau** [comment]
Konkretisierung:
der Link
/#/data/*collectionId*/preview
führt zu einer Seite
- mit den ersten 100 Einträgen der Collection *collectionId* als Tabelle
- der gesamten Antwort des REST-Servers als JSON

**Comment by JuliaH1** [comment]
Ist funktionsfähig. Die Überlegung wurde gemacht, bei Datensätzen ohne Daten also "null" Eine Art Meldung oder Text zb. "Der Datensatz enthält keine Daten!" zu machen

**Comment by SteffenPegenau** [comment]
Dieser Task ist abgeschlossen. Bei Bedarf neuen Issue erstellen.
