### ISSUE TITLE
WebGL: Darstellung der Verbindungen

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#46]
Gebäude erhalten einen geteilten Vorgarten: Die eine Hälfte bringt die eingehenden Verbindungen zum Ausdruck, die andere die ausgehenden. Die Verbindungszahl wird in der Größe des jeweiligen Vorgartens zum Ausdruck gebracht. Dadurch kann man auf einen Blick Gebäude identifizieren, die besonders viele/wenige Verbindungen haben. Klickt man auf einen Vorgarten werden die zugehörigen Verbindungen zu den Häusern in Form von Regenbögen angezeigt. Außerdem kann man - wenn man ein Gebäude ausgewählt hat - jeweils einen Haken "Eingehende [bzw. ausgehende] Verbindungen anzeigen".
Da die Vorgärten die Grundfläche des Gebäudes erweitern, ändert sich dadurch die Anordnung der Stadt.
Straßen fallen damit weg. Sie sind ätzend zu implementieren, sehen vor allem cool aus, aber liefern nur bedingt mehr Informationen.

**Comment by thuylinhluu** [comment]
- Die Verbindungen werden alle die gleiche Farbe haben, d.h. es werden einfarbige Fäden und keine Regenbögen.
- ich werde den Haken bei "Eingehende [bzw. ausgehende] Verbindungen anzeigen" weglassen, wenn man sich diese auch schon durch einen Klick auf den Vorgarten anzeigen lassen kann.
- Der linke Vorgarten soll die ausgehenden Verbindungen darstellen, der rechte soll die eingehenden darstellen (wie auch beim Straßenverkehr --> leicht zu merken).
- Klickt man auf den linken Vorgarten, werden dort alle ausgehenden Verbindungen angezeigt, die sollen dann zu den rechten Vorgärten der entsprechend anderen Gebäuden gehen.
- Klickt man auf den rechten Vorgarten, werden alle eingehenden Verbindungen angezeigt. Diese sollen dann zu den linken Vorgärten der anderen entsprechenden Gebäuden gehen.

Mir ist es ziemlich egal, welche Form die Daten zu den Verbindungen haben, ich werde mit allem umgehen können. Das Datenbank-Team oder wer auch immer kann sich gerne aussuchen, wie er die Daten importieren und mir überreichen möchte. Ich fände es toll, wenn sich dieser jemand auch mit mir in Verbindung setzt, sobald sie/er sich für eine Form entschieden hat, die für sie/ihn angenehm ist.

**Comment by JuliaH1** [comment]
Mir ist aufgefallen, dass wenn es Gebäude gibt, die sehr hoch sind, die Verbindungen ebenso sehr weit nach oben, aus dem Blickfeld herausragen und man damit nicht weiß, welche Verbindungen wohin zeigen. Vielleicht eine allgemeine Maximalhöhe der Bögen bestimmen?

**Comment by thuylinhluu** [comment]
Es ist zurzeit auf die Höhe des höchsten Gebäudes gesetzt.
Eine statische Obergrenze für die Höhe der Bögen zu setzen finde ich definitiv nicht sinnvoll (z.B. ich setze die maximale Höhe auf 100 und alle Gebäuden sind aber 10000 hoch, dann ist es nicht gut).
Ich kann natürlich den Höhendurchschnitt aller Gebäuden ausrechnen und die Standardabweichung und dann als Wert den Höhendurchschnitt + Standardabweichung als maximale Höhe nehmen. Aber wird das denn dann besser und sind die ganzen Iterationen über den kompletten Datensatz dafür denn wert?

**Comment by Nullmann** [comment]
Ich finde, dass das nicht nötig ist. Wenn man sich die Verbindungen ganz genau anzeigen lassen möchte, dann kann man auch die Höhe logarithmisch skalieren.

Ein schneller Fix wäre, dass man die Zoom-Stufe wieder frei gibt, also dass es da kein Maximum gibt.
