### ISSUE TITLE
Ansicht Datensätze: Meta-Daten garantieren

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#50]
Beim Selektieren eines Datensatzes soll sichergestellt sein, dass Meta-Daten vorhanden sind.

Dazu beim Selektieren prüfen, ob
* die Meta-Daten-Collection /prelife/*collectionname*_dc_stats existiert
* falls das nicht der Fall ist:
   * prüfen, ob Collection Aggregation maxminavg besitzt (Wenn nicht: anlegen)
   * Aggregation ausführen

**Comment by Nullmann** [comment]
Gehört das nicht schon in den Bereich automatische Tests?

**Comment by SteffenPegenau** [comment]
Nein, das hat mit Funktionstests nichts zu tun.

Es könnte sein, dass die Meta-Daten über einen Cron-Job angelegt wurden oder eben nicht. Um sicherzustellen, dass unser Skript auf jeden Fall auf die Daten zugreifen kann, muss garantiert sein, dass sie da sind.

**Comment by SteffenPegenau** [comment]
Mittlerweile geschlossen
