### ISSUE TITLE
Ansichten: Neue Routen erstellen

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#52]
Aktueller Stand:
/#/views/beispiel um Sich alle Ansichten zur Collection *beispiel* anzeigen zu lassen.

Es sollen zusätzliche Routen erstellt werden (app.js): 
* die direkt zu einer ausgewählten Ansicht führen (/#/views/beispiel/*idDerAnsicht*)
* die direkt die Stadt einer Ansicht zeichnen, ggf mit Parameterübergabe (/#/views/beispiel/*idDerAnsicht*/draw?angle=75.0&posX=40&...)

**Comment by JuliaH1** [comment]
Kleiner Bug wird noch behoben, dass man nicht zweimal die Ansicht auswählen muss
