### ISSUE TITLE
Datensätze: Invalid Date

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#58]
Frisch angelegte Collections werden mit korrektem Datum angezeigt. Sobald man sie einmal auswählt, wird in der Liste der Datensätze "Invalid Date" angezeigt.

**Comment by Nullmann** [comment]
Das liegt daran, dass bei der Erstellung eines Datensatzes dies in
```
collection._created_on4
```
hinterlegt ist, während das später bei der Erstellung der Metadaten unter
```
collection.metaData.timeOfCreation
```
geschieht. Wir bräuchten eine einheitliche Darstellung.
