### ISSUE TITLE
StringFilter für Ansichten->Daten reduzieren

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#59]
Dem Slider ähnlich soll es ein Eingabefeld für Strings geben.

**Comment by Nullmann** [comment]
Wie denkst du sollte dieser Filter aussehen? 

Am Einfachsten wäre vermutlich:
* Der Nutzer gibt einen String ein. Alle Strings, die damit beginnen oder diesen String enthalten, werden herausgefiltert (über regex)

**Comment by Nullmann** [comment]
Erstmal rausnehmen, sobald das nicht implementiert ist

**Comment by Nullmann** [comment]
Wurde rausgenommen
