### ISSUE TITLE
Hinweisfelder einbauen

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#60]
Der Anwender soll an verschiedenen Stellen Hinweise einblenden können.

**Comment by Nullmann** [comment]
Ich hab das bisher an verschiedenen Stellen über Hover-Overs eingebaut. Das funktioniert anscheinend soweit bei jedem html-tag. Beispiel:

<button type="button" class="btn btn-default" data-toggle="tooltip" title="Download" ng-click="downloadJSON()">
	<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
</button>

Alternativ könnte man auch die Tooltips von Bootstrap verwenden:
http://getbootstrap.com/javascript/#tooltips
bzw
http://www.w3schools.com/bootstrap/bootstrap_tooltip.asp

**Comment by thuylinhluu** [comment]
Ich versteh noch nicht so ganz, was das für Hinweise sein sollen... mag mir das jemand erklären?

**Comment by SteffenPegenau** [comment]
Einige Einstellungsmöglichkeiten sind vielleicht nicht direkt intuitiv verständlich. 

Beispielsweise die Blockbildung. Wie läuft die ab? Was gibt es für Parameter? Wie wirken die sich aus? 

Sowas könnte man als Pop-Up hinter einem Fragezeichen an der passenden Stelle verstecken
