### ISSUE TITLE
RESTHeart: Aufforderung zur Eingabe Benutzername/Passwort

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#64]
Bei einigen Aggregationsoperationen wird man aufgefordert Benutzername und Passwort einzugeben

**Comment by Nullmann** [comment]
Passiert anscheinend jedes mal, wenn man sich eine Stadt anzeigen lässt und das Passwort nicht im Cache o.Ä. ist (wenn der Browser neu gestartet wird etc )

**Comment by Nullmann** [comment]
Wenn man dort nichts eingibt, wird lediglich die Dimension "Klassen" in der Stadt nicht richtig angezeigt. Alle anderen schon.

**Comment by SteffenPegenau** [comment]
Vermutung: 
Bei diesem speziellen Aufruf muss statt dem Passwort ein mitgesendetes Token verwendet werden.
