### ISSUE TITLE
Auswählen, wie Blöcke dargestellt werden sollen

### ISSUE THREAD

**Issue by thuylinhluu** [Data-City/client#72]
Der Nutzer muss auswählen können, ob er keine Blockbildung, Blockbildung durch Punkte in Klassennamen oder Blockbildung durch Auswahl von Spalten haben möchte. Diese Information muss dem WebGL-Teil auch übergeben werden.

**Comment by Nullmann** [comment]
Es wird in der Ansicht nicht richtig gespeichert, aber richtig übergeben
