### ISSUE TITLE
WebGL: Farbanpassung per Config File

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#81]
Bisher nur eine Idee:
Die Farben der Darstellung lassen sich per settings.js anpassen

**Comment by Nullmann** [comment]
Bei den Associations wird dir nun das Attribut "buildingcolor" übergeben, welches in der settings.js (Im Ordner Controller) gesetzt wird.
Momentan ist es ein String mit dem Hexadezimalcode von #00008B, siehe
http://www.farb-tabelle.de/de/rgb2hex.htm?q=DarkBlue

**Comment by Nullmann** [comment]
Kann zu einem späteren Zeitpunkt fortgeführt und wieder geöffnet werden, ist momentan aber nichtvon Relevanz.

**Comment by thuylinhluu** [comment]
habs geschrieben, kann es hier aber gerade nicht testen. Probiers mal aus =)

**Comment by Nullmann** [comment]
Egal welchen Wert man in der Settings.js einträgt, die Stadt ist immer komplett weiß.
![weisse stadt](https://cloud.githubusercontent.com/assets/15816473/12747216/01afc8b4-c9a3-11e5-886c-8ffd1ad81e47.png)
