### ISSUE TITLE
Gebäude und Verbindungen highlighten

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#85]
Wenn man auf einen Vorgarten klickt, wird dieser ja hervorgehoben - schön wäre auch, wenn man mit der Maus über diesen Vorgarten drüberfährt, die anderen Vorgärten oder vielleicht eher die Gebäude gehighlightet werden können, zu denen eine Verbindung besteht

**Comment by Nullmann** [comment]
Ich finde, dass das dann zu unübersichtlich wird. Wenn man nur drüber hovern muss, weiß man am Ende gar nicht wo man die Maus haben darf, ohne Zusatzinformationen anzeigen zu lassen, besonders wenn man rangezoomt hat.

**Comment by Nullmann** [comment]
Falls jemand anderer Meinung ist, kann der Issue wieder geöffnet werden. Der Übersichtshalber schließe ich ihn.
