### ISSUE TITLE
Fixpunkt zurücksetzen

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#88]
Wenn in der Stadtansicht viel geschoben und gedreht wurde, bekommt man ab irgendeiner Stelle keine Kontrolle über die Steuerung. Da wäre es ganz praktisch, den Fixpunkt sozusagen wieder auf null zu setzen. Damit ist nicht gemeint, dass die Stadt zum Ausgangspunkt zurückgesetzt wird, sondern die Sicht bleibt - nur der Fixpunkt wird geändert, damit die Steuerung wieder geht

**Comment by thuylinhluu** [comment]
Man kann nicht den Fixpunkt ändern, ohne die Sicht zu ändern. Der Fixpunkt ist immer in der Mitte vom Bild.
