### ISSUE TITLE
Datensätze: Bearbeitungspanel

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#9]
Klickt man auf einen Datensatz soll sich ein Bearbeitungspanel (ähnlich wie bei Ansichten) öffnen. Dorthinsoll auch das "Löschen"-Symbol verschoben werden.

**Comment by Nullmann** [comment]
Wie bei den Ansichten, sollte dort auch wieder ein eigener Controller gebaut werden

**Comment by Nullmann** [comment]
Wurde eingebaut, aber nicht als Panel sondern als direkte Buttons (Vorschau, Datensatz löschen)
