### ISSUE TITLE
Verbindungen und Blockbildung

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#90]
Wenn man das Häckchen bei Verbindungen nutzen rein oder rausnimmt, während  bei der Blockbildung die dritte Option genutzt wird, sieht die Stadt sehr komisch aus, also die Gebäude werden nicht gezeichnet. Bei gruppieren nach jedem Punkt funktioniert es problemlos mit den Verbindungen

**Comment by Nullmann** [comment]
Bei sowas ist ggf. auch ein Screenshot hilfreich. So direkt kann man sich unter "sehr komisch" nichts vorstellen.

**Comment by JuliaH1** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/15839253/12531468/aabbb80a-c1fb-11e5-8de3-18035d147dfe.png)
