### ISSUE TITLE
Menü nachdem "Verbindungen" geändert wurden

### ISSUE THREAD

**Issue by JuliaH1** [Data-City/client#91]
Wenn man bei Verbindungen das Häckchen ändert, und die Stadt aktualisiert, zeigt das Menü nur noch die Legende und die Informationen

**Comment by Nullmann** [comment]
Kann ich nicht immer reproduzieren. Immer als das aufgetaucht ist hat ein Neuladen der Seite das Problem behoben.

**Comment by thuylinhluu** [comment]
Ich hoffe, es klappt nun. Falls es doch nicht geht, kann ja derjenige, dem das passiert, das issue wieder öffnen.
