### ISSUE TITLE
Link "aktuelle Ansicht" führt zu schwarzer Stadt

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#93]

**Comment by Nullmann** [comment]
Konnte ich bisher nur einmal reproduzieren, habe aber habe keine Regelmäßigkeit dahinter gefunden.

**Comment by JuliaH1** [comment]
Kann das geschlossen werden? Es funktioniert doch oder?

**Comment by Nullmann** [comment]
Dieser und Issue #91 wurden noch nicht gefixt und treten ggf. nochmal auf. Wann ist aber unklar.

**Comment by Nullmann** [comment]
Falls dieser Bug wieder auftritt, kann der Issue neu geöffnet werden.
