### ISSUE TITLE
Wenn auf eine stark gewichtete Verbindung geklickt wird, laggt es stark

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#94]
Das könnte sich lösen lassen, indem nur kleine "Regenbögen" gezeichnet werden. Die Gewichtung der Verbindungen werden doch bereits durch die Vorgärten gut visualisiert, oder?

**Comment by Nullmann** [comment]
Entscheidungen:
1) So lassen wie jetzt -> Gewichtung ist die Breite des Regenbogens
2) Breite kleiner; Gewichtung als Farbe darstellen -> GGf. Übersichtlichkeit geht verloren

**Comment by thuylinhluu** [comment]
Wäre es denn generell möglich, mir sowohl bei den Gebäuden den kleinsten Wert der Breite und Höhe mitzugeben, und bei den Verbindungen den kleinsten Wert > 0?

**Comment by Nullmann** [comment]
Bei den Gebäude könnten wir dir das hier übergeben: 

![metadata](https://cloud.githubusercontent.com/assets/15816473/12672767/e0f9c6ba-c678-11e5-8f1d-35c128a798c8.png)

Die Verbindungen bekommst du ja sowieso schon komplett übergeben.

**Comment by Nullmann** [comment]
Die oben gezeigten Metadaten werden bereits mitgegeben...

Lösung wäre es, alle Verbindungen gleich "breit" zu machen. Durch Issue #109 werden die Informationen in den Vorgärten gespeichert.
