### ISSUE TITLE
Wenn eine Stadt gespeichert ist, sollte keine Ansicht geändert oder  neue Stadt angezeigt werden

### ISSUE THREAD

**Issue by Nullmann** [Data-City/client#96]
Das verändert die gespeicherte Stadt, weil sie auf die Ansicht und die Collection "collID_dc_data" zugreift.

---> Sollte ggf. ins Benutzerhandbuch geschrieben werden

**Comment by thuylinhluu** [comment]
Ist dasselbe wie Issue #106 oder?

**Comment by Nullmann** [comment]
Ja, genau.
