### ISSUE TITLE
Fehlermeldung "Metadaten sind nicht vorhanden!"

### ISSUE THREAD

**Issue by SteffenPegenau** [Data-City/client#97]
Die Fehlermeldung wird auch angezeigt, wenn die Meta-Daten vorhanden sind

**Comment by Nullmann** [comment]
Das kommt daher, dass wir momentan nichtmal die benötigten Daten bei der Datenbank abfragen, sondern nur noch die Links zu den einzelnen Collections

**Comment by Nullmann** [comment]
Es gibt momentan keine schöne Möglichkeit die Metadaten auf der Seite anzeigen zu lassen, ohne zusätzliche Anfragen beim Server zu starten.
Deswegen habe ich die Anzahl der Einträge in die Vorschau ausgelagert.
Das Objekt der "richtigen" Collection scheint nichtmal mehr das Attribut "_created_on" zu besitzen.
